from __future__ import annotations

import json
import subprocess
import sys
import tomllib
from pathlib import Path

import pytest

from scripts.ai_sync import (
    CLAUDE_BRIDGE_FILE,
    CLAUDE_BRIDGE_MARKER,
    DEFAULT_OUTPUT_NAME,
    SEVERITY_ERROR,
    DoctorReport,
    SyncError,
    _build_managed_template_content,
    _strip_frontmatter,
    build_rendered_content,
    check,
    init_claude_bridge,
    init_project,
    render,
    run_doctor,
    run_repair,
    sync_project_templates,
    write_rendered_content,
)

REPO_ROOT = Path(__file__).resolve().parents[1]
CURRENT_AI_STANDARDS_VERSION = "2.2.0"
CURRENT_RELEASE_DATE = "2026-08-28"
MANIFEST_RELEASE_BLOCK = (
    f'ai_standards_version = "{CURRENT_AI_STANDARDS_VERSION}"\n'
    f'project_version = "{CURRENT_AI_STANDARDS_VERSION}"\n'
    f'project_release_date = "{CURRENT_RELEASE_DATE}"\n'
)


def test_render_contains_expected_markers(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)

    manifest = (
        MANIFEST_RELEASE_BLOCK +
        'fragments = [\n'
        '  "core/base",\n'
        '  "core/git-workflow",\n'
        '  "core/architecture",\n'
        '  "core/error-handling",\n'
        ']\n'
        'features = [\n'
        '  "conport",\n'
        '  "basic-memory",\n'
        '  "design-first-collaboration",\n'
        '  "structured-artifacts",\n'
        ']\n'
        'stacks = ["python", "fastapi", "vue"]\n'
        'local_overrides = ["docs/ai/project-rules.md"]\n'
        'optional_local_overrides = ["docs/ai/private-rules.local.md"]\n'
        "\n"
        "[metadata]\n"
        'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )
    (project_root / "docs" / "ai" / "private-rules.local.md").write_text(
        "# Private AI Rules\n\n- Private local override.\n",
        encoding="utf-8",
    )

    result = build_rendered_content(project_root)

    assert (
        f"Generated by ai-standards v{CURRENT_AI_STANDARDS_VERSION} "
        f"release date: {CURRENT_RELEASE_DATE}"
    ) in result.content
    assert (
        f"Project version: {CURRENT_AI_STANDARDS_VERSION} "
        f"release date: {CURRENT_RELEASE_DATE}"
    ) in result.content
    assert f"<!-- Source: {REPO_ROOT}" not in result.content
    assert f"<!-- Project: {project_root}" not in result.content
    assert "## Design-First Collaboration" in result.content
    assert "## Basic Memory Usage" in result.content
    assert "## Lightweight Structured Artifacts" in result.content
    assert "## FastAPI Stack" in result.content
    assert "## Vue Stack" in result.content
    assert "Demo override." in result.content
    assert "Private local override." in result.content


def test_basic_memory_feature_renders_reindexing_guidance(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)

    manifest = (
        MANIFEST_RELEASE_BLOCK
        + 'fragments = ["core/base"]\n'
        + 'features = ["basic-memory"]\n'
        + 'stacks = ["python"]\n'
        + 'local_overrides = ["docs/ai/project-rules.md"]\n'
        + "\n"
        + "[metadata]\n"
        + 'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )

    result = build_rendered_content(project_root)

    assert "## Basic Memory Usage" in result.content
    assert "never at a repository root" in result.content
    assert "Keep permalink generation enabled" in result.content
    assert "After `git pull`, `git merge`, `git rebase`, branch switches" in result.content


def test_java_spring_stack_alias_can_be_rendered(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)

    manifest = (
        MANIFEST_RELEASE_BLOCK +
        'fragments = ["core/base", "core/architecture", "core/error-handling"]\n'
        'features = ["conport"]\n'
        'stacks = ["java-spring"]\n'
        'local_overrides = ["docs/ai/project-rules.md"]\n'
        "\n"
        "[metadata]\n"
        'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )

    result = build_rendered_content(project_root)

    assert "## Java Stack" in result.content
    assert "## Spring Stack" in result.content
    assert "## Spring Data JPA Stack" in result.content
    assert "Use constructor injection by default" in result.content


def test_explicit_java_spring_stack_combination_can_be_rendered(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)

    manifest = (
        MANIFEST_RELEASE_BLOCK +
        'fragments = ["core/base", "core/architecture", "core/error-handling"]\n'
        'features = ["conport"]\n'
        'stacks = ["java", "spring", "spring-data-jpa"]\n'
        'local_overrides = ["docs/ai/project-rules.md"]\n'
        "\n"
        "[metadata]\n"
        'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )

    result = build_rendered_content(project_root)

    assert "Use modern Java idioms supported by the repository baseline" in result.content
    assert (
        "Standardize REST error responses through centralized exception handling"
        in result.content
    )
    assert "Treat fetch plans deliberately" in result.content


def test_legacy_manifest_version_key_still_renders(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)

    manifest = (
        'version = "0.1.0"\n'
        'project_version = "0.1.0"\n'
        'project_release_date = "2026-04-15"\n'
        'fragments = ["core/base"]\n'
        'features = ["conport"]\n'
        'stacks = ["python"]\n'
        'local_overrides = ["docs/ai/project-rules.md"]\n'
        "\n"
        "[metadata]\n"
        'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )

    result = build_rendered_content(project_root)

    assert (
        f"Generated by ai-standards v{CURRENT_AI_STANDARDS_VERSION} "
        f"release date: {CURRENT_RELEASE_DATE}"
    ) in result.content
    assert "<!-- Requested ai-standards version: 0.1.0 -->" in result.content


def test_typescript_stack_can_be_rendered(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)

    manifest = (
        MANIFEST_RELEASE_BLOCK +
        'fragments = ["core/base", "core/error-handling"]\n'
        'features = ["conport"]\n'
        'stacks = ["typescript", "react"]\n'
        'local_overrides = ["docs/ai/project-rules.md"]\n'
        "\n"
        "[metadata]\n"
        'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )

    result = build_rendered_content(project_root)

    assert "## TypeScript Stack" in result.content
    assert "Use `satisfies` when you need to verify object shape" in result.content
    assert "## React Stack" in result.content
    assert (
        "Treat Effects as an escape hatch for synchronizing with external systems"
        in result.content
    )
    assert "When reading mutable state from outside React" in result.content


def test_vue_stack_renders_modern_guidance(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)

    manifest = (
        MANIFEST_RELEASE_BLOCK
        + 'fragments = ["core/base", "core/error-handling"]\n'
        + 'features = ["conport"]\n'
        + 'stacks = ["typescript", "vue"]\n'
        + 'local_overrides = ["docs/ai/project-rules.md"]\n'
        + "\n"
        + "[metadata]\n"
        + 'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )

    result = build_rendered_content(project_root)

    assert "## Vue Stack" in result.content
    assert "prefer `<script setup>` as the default authoring style" in result.content
    assert "Prefer `computed` for derived state" in result.content
    assert "return a plain object of refs by default" in result.content


def test_nextjs_stack_renders_framework_guidance(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)

    manifest = (
        MANIFEST_RELEASE_BLOCK
        + 'fragments = ["core/base", "core/error-handling"]\n'
        + 'features = ["conport"]\n'
        + 'stacks = ["typescript", "react", "nextjs"]\n'
        + 'local_overrides = ["docs/ai/project-rules.md"]\n'
        + "\n"
        + "[metadata]\n"
        + 'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )

    result = build_rendered_content(project_root)

    assert "## Next.js Stack" in result.content
    assert "Treat Server Components as the default rendering boundary" in result.content
    assert "Use Server Actions for form-style mutations" in result.content
    assert "Provide route-level `loading`, `error`, and `not-found` boundaries" in result.content


def test_tanstack_query_stack_can_be_rendered_with_react(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)

    manifest = (
        MANIFEST_RELEASE_BLOCK
        + 'fragments = ["core/base", "core/error-handling"]\n'
        + 'features = ["conport"]\n'
        + 'stacks = ["typescript", "react", "tanstack-query"]\n'
        + 'local_overrides = ["docs/ai/project-rules.md"]\n'
        + "\n"
        + "[metadata]\n"
        + 'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )

    result = build_rendered_content(project_root)

    assert "## TanStack Query Stack" in result.content
    assert "Use TanStack Query for server-state synchronization" in result.content
    assert "Keep query keys stable, structured, and domain-meaningful" in result.content
    assert "After mutations, revalidate affected server state deliberately" in result.content


def test_nuxt_vite_and_fsd_stacks_can_be_rendered_together(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)

    manifest = (
        MANIFEST_RELEASE_BLOCK
        + 'fragments = ["core/base", "core/error-handling"]\n'
        + 'features = ["conport"]\n'
        + 'stacks = ["typescript", "vue", "nuxt", "vite", "fsd"]\n'
        + 'local_overrides = ["docs/ai/project-rules.md"]\n'
        + "\n"
        + "[metadata]\n"
        + 'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )

    result = build_rendered_content(project_root)

    assert "## Nuxt Stack" in result.content
    assert (
        "Prefer `useFetch` or `useAsyncData` for SSR-friendly page and layout data"
        in result.content
    )
    assert (
        "Configure rendering and caching behavior intentionally with route rules"
        in result.content
    )
    assert "## Vite Stack" in result.content
    assert (
        "Access browser-exposed environment variables through `import.meta.env`"
        in result.content
    )
    assert "Prefer dynamic imports, route-level splitting" in result.content
    assert "## Feature-Sliced Design Stack" in result.content
    assert "Expose a deliberate public API for each slice or shared segment" in result.content


def test_vue_query_alias_can_be_rendered(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)

    manifest = (
        MANIFEST_RELEASE_BLOCK
        + 'fragments = ["core/base", "core/error-handling"]\n'
        + 'features = ["conport"]\n'
        + 'stacks = ["typescript", "vue-query"]\n'
        + 'local_overrides = ["docs/ai/project-rules.md"]\n'
        + "\n"
        + "[metadata]\n"
        + 'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )

    result = build_rendered_content(project_root)

    assert "## Vue Stack" in result.content
    assert "## TanStack Query Stack" in result.content
    assert "derived view state and reusable logic" in result.content
    assert "Keep query keys stable, structured, and domain-meaningful" in result.content


def test_python_stack_renders_unified_guidance(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)

    manifest = (
        MANIFEST_RELEASE_BLOCK
        + 'fragments = ["core/base", "core/error-handling"]\n'
        + 'features = ["conport"]\n'
        + 'stacks = ["python"]\n'
        + 'local_overrides = ["docs/ai/project-rules.md"]\n'
        + "\n"
        + "[metadata]\n"
        + 'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )

    result = build_rendered_content(project_root)

    assert "Use type hints for public and shared module boundaries" in result.content
    assert (
        "Use `match` for closed variants, tagged states, and structural patterns"
        in result.content
    )
    assert "## Python Stack" in result.content
    assert "Avoid `Any` as a convenience shortcut" in result.content
    assert "Prefer `pathlib.Path` over stringly-typed path handling" in result.content
    assert "Prefer logging for application and library diagnostics" in result.content


def test_django_and_fastapi_stacks_render_updated_guidance(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)

    manifest = (
        MANIFEST_RELEASE_BLOCK
        + 'fragments = ["core/base", "core/error-handling"]\n'
        + 'features = ["conport"]\n'
        + 'stacks = ["django", "fastapi"]\n'
        + 'local_overrides = ["docs/ai/project-rules.md"]\n'
        + "\n"
        + "[metadata]\n"
        + 'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )

    result = build_rendered_content(project_root)

    assert "## Django Stack" in result.content
    assert "Use transactions deliberately around multi-step writes" in result.content
    assert "Prefer Django's built-in protections and conventions" in result.content
    assert "## FastAPI Stack" in result.content
    assert "Use explicit response contracts via `response_model`" in result.content
    assert "Use `lifespan` for application startup and shutdown resources" in result.content
    assert "Raise `HTTPException` at the HTTP boundary" in result.content


def test_django_drf_stack_renders_softened_guidance(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)

    manifest = (
        MANIFEST_RELEASE_BLOCK
        + 'fragments = ["core/base", "core/error-handling"]\n'
        + 'features = ["conport"]\n'
        + 'stacks = ["django-drf"]\n'
        + 'local_overrides = ["docs/ai/project-rules.md"]\n'
        + "\n"
        + "[metadata]\n"
        + 'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )

    result = build_rendered_content(project_root)

    assert "## Django REST Framework" in result.content
    assert "Choose `APIView`, generic views, or viewsets" in result.content
    assert "Use `Serializer` or `ModelSerializer` deliberately" in result.content
    assert "Validate incoming data at the API boundary" in result.content


def test_django_service_layer_and_save_orchestration_render(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)

    manifest = (
        MANIFEST_RELEASE_BLOCK
        + 'fragments = ["core/base", "core/error-handling"]\n'
        + 'features = ["conport"]\n'
        + 'stacks = ["django", "django-service-layer", "django-save-orchestration"]\n'
        + 'local_overrides = ["docs/ai/project-rules.md"]\n'
        + "\n"
        + "[metadata]\n"
        + 'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )

    result = build_rendered_content(project_root)

    assert "## Layered Architecture" in result.content
    assert "## Backend Layered Architecture" in result.content
    assert "## Django Service Layer" in result.content
    assert "This fragment is an opt-in architectural style" in result.content
    assert "Place write operations (create, update, delete) in service functions" in result.content
    assert "## Django Save Orchestration" in result.content
    assert "perform_create()` and `perform_update()` may delegate" in result.content
    assert "schedule it with `transaction.on_commit`" in result.content


def test_frontend_layered_architecture_stack_can_be_rendered(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)

    manifest = (
        MANIFEST_RELEASE_BLOCK
        + 'fragments = ["core/base", "core/error-handling"]\n'
        + 'features = ["conport"]\n'
        + 'stacks = ["react", "frontend-layered-architecture"]\n'
        + 'local_overrides = ["docs/ai/project-rules.md"]\n'
        + "\n"
        + "[metadata]\n"
        + 'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )

    result = build_rendered_content(project_root)

    assert "## Frontend Layered Architecture" in result.content
    assert "Expose public APIs for architectural units" in result.content
    assert (
        "Keep framework bootstrap, routing setup, and environment wiring separate"
        in result.content
    )


def test_review_lenses_feature_can_be_rendered(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)

    manifest = (
        MANIFEST_RELEASE_BLOCK +
        'fragments = ["core/base", "core/architecture"]\n'
        'features = ["review-lenses"]\n'
        'stacks = ["python"]\n'
        'local_overrides = ["docs/ai/project-rules.md"]\n'
        "\n"
        "[metadata]\n"
        'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )

    result = build_rendered_content(project_root)

    assert "## Multi-Lens Review" in result.content
    assert (
        "Quality over Efficiency when safety, readability, or correctness is at risk."
        in result.content
    )
    assert "### DRY" in result.content


def test_code_review_feature_can_be_rendered(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)

    manifest = (
        MANIFEST_RELEASE_BLOCK +
        'fragments = ["core/base", "core/architecture"]\n'
        'features = ["code-review"]\n'
        'stacks = ["python"]\n'
        'local_overrides = ["docs/ai/project-rules.md"]\n'
        "\n"
        "[metadata]\n"
        'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )

    result = build_rendered_content(project_root)

    # Assert on stable identifiers only: the fragment heading, the activation rule, and
    # the pointer to the file that defines the report shape. Prose wording is deliberately
    # not asserted, so rewording the guidance does not break this test.
    assert "## Code Review" in result.content
    assert ".ai-standards/code-review-report.md" in result.content
    assert "### Fixing While Reviewing" in result.content
    assert (
        'Treat a bare, unqualified request such as "code review"' in result.content
    )


def test_report_template_sections_stay_in_sync_with_the_fragment() -> None:
    """Guard the two places that unavoidably restate the report shape.

    `templates/code-review-report.md` defines the shape, but the fragment has to name the
    sections twice anyway: once in the fallback ordering used when a project never synced
    the template, and once in the localization mapping. Renaming a section in the template
    must therefore fail here rather than silently diverge from those two lists.
    """
    template = (REPO_ROOT / "templates" / "code-review-report.md").read_text(encoding="utf-8")
    fragment = (REPO_ROOT / "fragments" / "process" / "code-review.md").read_text(
        encoding="utf-8"
    )

    sections = [
        line.removeprefix("### ").strip()
        for line in template.splitlines()
        if line.startswith("### ")
    ]
    assert sections, "the worked example must define the report sections"

    lines = fragment.splitlines()
    fallback = next(line for line in lines if "fall back to this order" in line)
    mapping = next(line for line in lines if "For Russian use" in line)

    for section in sections:
        assert section in fallback, f"{section!r} is missing from the fragment fallback ordering"
        assert section in mapping, f"{section!r} is missing from the localization mapping"

    assert "Code Review" in mapping
    assert "Task" in fallback and "Task" in mapping

    # The example teaches the linked form of the task reference, not the bare id.
    task_line = next(line for line in template.splitlines() if line.startswith("Task:"))
    assert "http" in task_line, "the worked example must show a task link, not just an id"

    # The example opens with the ai-standards version line, and the fragment names the
    # header that version comes from; dropping either must fail here rather than diverge.
    version_lines = [
        line.strip() for line in template.splitlines() if line.startswith("ai-standards ")
    ]
    assert version_lines, "the worked example must carry the ai-standards version line"
    version_rule = next(
        line for line in lines if "ai-standards" in line and "version" in line
    )
    assert "Generated by ai-standards" in version_rule


def test_module_contract_gate_feature_can_be_rendered(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)

    manifest = (
        MANIFEST_RELEASE_BLOCK +
        'fragments = ["core/base", "core/architecture"]\n'
        'features = ["module-contract-gate"]\n'
        'stacks = ["python"]\n'
        'local_overrides = ["docs/ai/project-rules.md"]\n'
        "\n"
        "[metadata]\n"
        'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )

    result = build_rendered_content(project_root)

    # Assert on stable identifiers only: the fragment heading, the strict rule, and
    # the proportional exit. Prose wording is deliberately not asserted.
    assert "## Module Contract Discovery Gate" in result.content
    assert (
        "Do not edit production code until module-contract discovery" in result.content
    )
    assert "discovery is complete with that result" in result.content
    # The composite carries the contracts policy the gate presumes.
    assert "## Module Contracts" in result.content


def test_module_contract_gate_fragment_keeps_its_guarantees() -> None:
    fragment = (
        REPO_ROOT / "fragments" / "process" / "module-contract-gate.md"
    ).read_text(encoding="utf-8")
    flat = " ".join(fragment.split())

    # The guarantee: no production-code edit before discovery completes.
    assert (
        "Do not edit production code until module-contract discovery for the touched "
        "files has completed." in flat
    )
    # The proportionality: a declared absence of contracts completes discovery.
    assert "discovery is complete with that result" in flat
    # Basic Memory steps stay conditional on the feature being enabled.
    assert "when `basic-memory` is enabled" in flat
    # Violations escalate through the existing stop conditions, not a duplicate.
    assert "`Autonomy Boundaries`" in flat


def test_response_language_style_feature_can_be_rendered(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)

    manifest = (
        MANIFEST_RELEASE_BLOCK +
        'fragments = ["core/base", "core/architecture"]\n'
        'features = ["response-language-style"]\n'
        'stacks = ["python"]\n'
        'local_overrides = ["docs/ai/project-rules.md"]\n'
        "\n"
        "[metadata]\n"
        'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )

    result = build_rendered_content(project_root)

    # Assert on stable identifiers only: the fragment heading and the two rules the
    # feature exists for. Prose wording is deliberately not asserted.
    assert "## Response Language Style" in result.content
    assert "write natural Russian" in result.content
    assert "срок" in result.content
    assert "дедлайн" in result.content


def test_response_language_style_fragment_keeps_its_rules() -> None:
    fragment = (
        REPO_ROOT / "fragments" / "process" / "response-language-style.md"
    ).read_text(encoding="utf-8")
    flat = " ".join(fragment.split())

    assert 'prefer "срок" over "дедлайн", "согласование" over "апрув"' in flat
    assert "must not appear without an immediate explanation" in flat
    assert "expand them with a short Russian explanation" in flat
    assert "not code, identifiers, or commit messages" in flat


def test_reasoning_hygiene_feature_can_be_rendered(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)

    manifest = (
        MANIFEST_RELEASE_BLOCK +
        'fragments = ["core/base", "core/architecture"]\n'
        'features = ["reasoning-hygiene"]\n'
        'stacks = ["python"]\n'
        'local_overrides = ["docs/ai/project-rules.md"]\n'
        "\n"
        "[metadata]\n"
        'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )

    result = build_rendered_content(project_root)

    assert "## Reasoning Hygiene" in result.content
    assert (
        "Reject prompt tricks that rely on incentives, emotional pressure, or challenge language"
        in result.content
    )


def test_autonomy_boundaries_feature_can_be_rendered(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)

    manifest = (
        MANIFEST_RELEASE_BLOCK +
        'fragments = ["core/base", "core/architecture"]\n'
        'features = ["autonomy-boundaries"]\n'
        'stacks = ["python"]\n'
        'local_overrides = ["docs/ai/project-rules.md"]\n'
        "\n"
        "[metadata]\n"
        'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )

    result = build_rendered_content(project_root)

    assert "## Autonomy Boundaries" in result.content
    assert (
        "Stop when a new abstraction, architectural layer, public contract change,"
        in result.content
    )


def test_structured_artifacts_feature_can_be_rendered(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)

    manifest = (
        MANIFEST_RELEASE_BLOCK +
        'fragments = ["core/base", "core/architecture"]\n'
        'features = ["structured-artifacts"]\n'
        'stacks = ["python"]\n'
        'local_overrides = ["docs/ai/project-rules.md"]\n'
        "\n"
        "[metadata]\n"
        'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )

    result = build_rendered_content(project_root)

    assert "## Lightweight Structured Artifacts" in result.content
    assert (
        "Create `MODULE_CONTRACT.md` only for major, risky, shared, or "
        "architecturally non-obvious modules." in result.content
    )


def test_agent_usage_hygiene_feature_can_be_rendered(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)

    manifest = (
        MANIFEST_RELEASE_BLOCK +
        'fragments = ["core/base", "core/architecture"]\n'
        'features = ["agent-usage-hygiene"]\n'
        'stacks = ["python"]\n'
        'local_overrides = ["docs/ai/project-rules.md"]\n'
        "\n"
        "[metadata]\n"
        'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )

    result = build_rendered_content(project_root)

    assert "## Agent Usage Hygiene" in result.content
    assert (
        "Enter economy mode only when the user explicitly asks to be economical"
        in result.content
    )


def test_session_hygiene_feature_can_be_rendered(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)

    manifest = (
        MANIFEST_RELEASE_BLOCK +
        'fragments = ["core/base", "core/architecture"]\n'
        'features = ["session-hygiene"]\n'
        'stacks = ["python"]\n'
        'local_overrides = ["docs/ai/project-rules.md"]\n'
        "\n"
        "[metadata]\n"
        'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )

    result = build_rendered_content(project_root)

    assert "## Session Hygiene" in result.content
    assert (
        "Warn the user when a long thread increases the risk of context drift"
        in result.content
    )


def test_written_file_matches_rendered_content(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "ai").mkdir(parents=True)

    (project_root / "ai.project.toml").write_text(
        (REPO_ROOT / "templates" / "project_manifest.toml").read_text(encoding="utf-8"),
        encoding="utf-8",
    )
    (project_root / "ai" / "project-rules.md").write_text(
        (REPO_ROOT / "templates" / "project_rules.md").read_text(encoding="utf-8"),
        encoding="utf-8",
    )

    result = build_rendered_content(project_root)
    write_rendered_content(result)

    assert result.output_path.read_text(encoding="utf-8") == result.content


def test_render_cli_accepts_default_output_name_with_typer_024_plus(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "ai").mkdir(parents=True)

    (project_root / "ai.project.toml").write_text(
        (REPO_ROOT / "templates" / "project_manifest.toml").read_text(encoding="utf-8"),
        encoding="utf-8",
    )
    (project_root / "ai" / "project-rules.md").write_text(
        (REPO_ROOT / "templates" / "project_rules.md").read_text(encoding="utf-8"),
        encoding="utf-8",
    )

    result = subprocess.run(
        [
            sys.executable,
            str(REPO_ROOT / "scripts" / "ai_sync.py"),
            "render",
            "--project-root",
            str(project_root),
        ],
        capture_output=True,
        text=True,
        check=False,
    )

    assert result.returncode == 0, result.stderr
    assert (project_root / "AGENTS.md").exists()


def test_init_project_seeds_current_ai_standards_version(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()

    init_project(project_root)

    manifest = (project_root / "ai.project.toml").read_text(encoding="utf-8")

    assert f'ai_standards_version = "{CURRENT_AI_STANDARDS_VERSION}"' in manifest
    assert 'project_version = "replace-me"' in manifest


def test_init_claude_bridge_creates_claude_md(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()

    init_claude_bridge(project_root)

    bridge_path = project_root / CLAUDE_BRIDGE_FILE
    assert bridge_path.exists()
    content = bridge_path.read_text(encoding="utf-8")
    assert CLAUDE_BRIDGE_MARKER in content
    assert f"@{DEFAULT_OUTPUT_NAME}" in content


def test_init_claude_bridge_respects_custom_output_name(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()

    init_claude_bridge(project_root, output_name="CUSTOM.md")

    content = (project_root / CLAUDE_BRIDGE_FILE).read_text(encoding="utf-8")
    assert "@CUSTOM.md" in content


def test_init_claude_bridge_skips_unmanaged_claude_md(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    existing_content = "# My custom CLAUDE.md\n\nDo not overwrite me.\n"
    (project_root / CLAUDE_BRIDGE_FILE).write_text(existing_content, encoding="utf-8")

    init_claude_bridge(project_root)

    assert (project_root / CLAUDE_BRIDGE_FILE).read_text(encoding="utf-8") == existing_content


def test_init_claude_bridge_updates_managed_claude_md(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()

    init_claude_bridge(project_root, output_name="OLD.md")
    init_claude_bridge(project_root, output_name="NEW.md")

    content = (project_root / CLAUDE_BRIDGE_FILE).read_text(encoding="utf-8")
    assert "@NEW.md" in content
    assert "@OLD.md" not in content


def test_ai_sync_console_script_resolves_help(tmp_path: Path) -> None:
    result = subprocess.run(
        ["uv", "run", "ai-sync", "--help"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=False,
    )

    assert result.returncode == 0
    assert "Usage: ai-sync" in result.stdout


def test_missing_optional_override_does_not_fail(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)

    manifest = (
        MANIFEST_RELEASE_BLOCK +
        'fragments = ["core/base", "core/architecture"]\n'
        'features = ["conport"]\n'
        'stacks = ["python"]\n'
        'local_overrides = ["docs/ai/project-rules.md"]\n'
        'optional_local_overrides = ["docs/ai/private-rules.local.md"]\n'
        "\n"
        "[metadata]\n"
        'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )

    result = build_rendered_content(project_root)

    assert "Demo override." in result.content
    assert "private-rules.local" not in result.content


def test_sync_project_templates_creates_agent_adapters_from_manifest(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)

    manifest = (
        MANIFEST_RELEASE_BLOCK +
        'fragments = ["core/base", "core/architecture"]\n'
        'features = ["review-lenses"]\n'
        'stacks = ["python"]\n'
        'local_overrides = ["docs/ai/project-rules.md"]\n'
        "\n"
        "[tooling]\n"
        'agents = ["codex", "cursor"]\n'
        "\n"
        "[metadata]\n"
        'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )

    results = sync_project_templates(project_root)

    # simplify-review for both agents, plus the always-deployed update skill.
    assert [result.status for result in results] == ["created"] * 4
    codex_skill = project_root / ".codex/skills/review-lenses/simplify-review/SKILL.md"
    cursor_rule = project_root / ".cursor/rules/simplify-review.mdc"
    assert codex_skill.exists()
    assert cursor_rule.exists()
    assert "Managed by ai-standards template:" in codex_skill.read_text(encoding="utf-8")
    assert "Managed by ai-standards template:" in cursor_rule.read_text(encoding="utf-8")


def test_sync_project_templates_updates_plain_copied_template(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)
    (project_root / ".cursor/rules").mkdir(parents=True)

    manifest = (
        MANIFEST_RELEASE_BLOCK +
        'fragments = ["core/base", "core/architecture"]\n'
        'features = ["review-lenses"]\n'
        'stacks = ["python"]\n'
        'local_overrides = ["docs/ai/project-rules.md"]\n'
        "\n"
        "[tooling]\n"
        'agents = ["cursor"]\n'
        "\n"
        "[metadata]\n"
        'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )
    raw_template = (
        REPO_ROOT / "templates" / "review-lenses" / "simplify-review.cursor.mdc"
    ).read_text(encoding="utf-8")
    destination = project_root / ".cursor/rules/simplify-review.mdc"
    destination.write_text(raw_template, encoding="utf-8")

    results = sync_project_templates(project_root)

    # The pre-copied simplify-review rule updates in place; the update skill is new.
    assert [result.status for result in results] == ["updated", "created"]
    assert "Managed by ai-standards template:" in destination.read_text(encoding="utf-8")


def test_sync_project_templates_skips_unmanaged_local_changes(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)
    (project_root / ".cursor/rules").mkdir(parents=True)

    manifest = (
        MANIFEST_RELEASE_BLOCK +
        'fragments = ["core/base", "core/architecture"]\n'
        'features = ["review-lenses"]\n'
        'stacks = ["python"]\n'
        'local_overrides = ["docs/ai/project-rules.md"]\n'
        "\n"
        "[tooling]\n"
        'agents = ["cursor"]\n'
        "\n"
        "[metadata]\n"
        'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )
    destination = project_root / ".cursor/rules/simplify-review.mdc"
    destination.write_text("# custom local rule\n", encoding="utf-8")

    results = sync_project_templates(project_root)

    # The unmanaged rule stays untouched; the update skill still deploys.
    assert [result.status for result in results] == ["skipped-unmanaged", "created"]
    assert destination.read_text(encoding="utf-8") == "# custom local rule\n"


def test_managed_marker_keeps_toml_parseable() -> None:
    managed = _build_managed_template_content(
        "templates/ai-infrastructure/code-index.toml",
        ".ai-standards/code-index.toml",
        'workspace = ".."\n\n[[collection]]\nname = "code"\nroots = ["src"]\n',
    )

    assert managed.startswith("# Managed by ai-standards template:")
    assert "<!--" not in managed
    assert tomllib.loads(managed)["workspace"] == ".."


def test_managed_marker_keeps_python_compilable_and_shebang_first() -> None:
    source = "#!/usr/bin/env -S uv run --script\nprint(\"ok\")\n"

    managed = _build_managed_template_content(
        "templates/ai-infrastructure/scripts/code_index.py",
        ".ai-standards/scripts/code_index.py",
        source,
    )

    lines = managed.splitlines()
    expected_source = "templates/ai-infrastructure/scripts/code_index.py"
    assert lines[0] == "#!/usr/bin/env -S uv run --script"
    assert lines[1] == f"# Managed by ai-standards template: {expected_source}"
    compile(managed, "code_index.py", "exec")


def test_managed_marker_keeps_html_form_for_markdown_destinations() -> None:
    managed = _build_managed_template_content(
        "templates/review-lenses/simplify-review.SKILL.md",
        ".codex/skills/review-lenses/simplify-review/SKILL.md",
        "# Simplify Review\n",
    )

    assert managed.startswith("<!-- Managed by ai-standards template:")
    assert "# Managed by ai-standards template:" not in managed


def test_sync_deploys_parseable_chroma_infra_templates(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)

    manifest = (
        MANIFEST_RELEASE_BLOCK +
        'fragments = ["core/base"]\n'
        'features = ["chroma"]\n'
        'stacks = ["python"]\n'
        'local_overrides = ["docs/ai/project-rules.md"]\n'
        "\n"
        "[tooling]\n"
        "agents = []\n"
        "\n"
        "[metadata]\n"
        'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )

    sync_project_templates(project_root)

    index_toml = project_root / ".ai-standards" / "code-index.toml"
    index_py = project_root / ".ai-standards" / "scripts" / "code_index.py"
    assert tomllib.loads(index_toml.read_text(encoding="utf-8"))["workspace"] == ".."
    python_source = index_py.read_text(encoding="utf-8")
    assert python_source.startswith("#!/usr/bin/env")
    compile(python_source, "code_index.py", "exec")


def test_code_review_fragment_names_module_contracts() -> None:
    fragment = (
        REPO_ROOT / "fragments" / "process" / "code-review.md"
    ).read_text(encoding="utf-8")
    template = (
        REPO_ROOT / "templates" / "code-review-report.md"
    ).read_text(encoding="utf-8")

    assert "MODULE_CONTRACT.md" in fragment
    assert "docs/architecture/**" in fragment
    assert "(no contract)" in fragment
    assert "violates: MODULE_CONTRACT.md" in template


def test_sync_deploys_capture_knowledge_adapters_when_feature_enabled(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)

    manifest = (
        MANIFEST_RELEASE_BLOCK +
        'fragments = ["core/base"]\n'
        'features = ["knowledge-capture"]\n'
        'stacks = ["python"]\n'
        'local_overrides = ["docs/ai/project-rules.md"]\n'
        "\n"
        "[tooling]\n"
        'agents = ["codex", "cursor", "claude", "kilo"]\n'
        "\n"
        "[metadata]\n"
        'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )

    sync_project_templates(project_root)

    for adapter in (
        ".codex/skills/knowledge-capture/capture-knowledge/SKILL.md",
        ".agents/skills/knowledge-capture/capture-knowledge/SKILL.md",
        ".claude/commands/capture-knowledge.md",
        ".cursor/rules/capture-knowledge.mdc",
    ):
        content = (project_root / adapter).read_text(encoding="utf-8")
        assert "зафиксируй знания стандартным образом" in content, adapter


def test_capture_knowledge_feature_renders_only_its_pointer_fragment(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)
    (project_root / "ai").mkdir()

    manifest = (
        MANIFEST_RELEASE_BLOCK +
        'fragments = ["core/base"]\n'
        'features = ["knowledge-capture"]\n'
        'stacks = ["python"]\n'
        'local_overrides = ["ai/project-rules.md"]\n'
        "\n"
        "[metadata]\n"
        'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")
    (project_root / "ai" / "project-rules.md").write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )

    result = build_rendered_content(project_root)

    result = build_rendered_content(project_root)

    assert result.fragment_ids == ["core/base", "process/knowledge-capture", "stacks/python"]
    assert "зафиксируй знания стандартным образом" in result.content


def test_unknown_agent_in_manifest_raises_sync_error(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)

    manifest = (
        MANIFEST_RELEASE_BLOCK +
        'fragments = ["core/base", "core/architecture"]\n'
        'features = ["review-lenses"]\n'
        'stacks = ["python"]\n'
        'local_overrides = ["docs/ai/project-rules.md"]\n'
        "\n"
        "[tooling]\n"
        'agents = ["vscode"]\n'
        "\n"
        "[metadata]\n"
        'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )

    try:
        build_rendered_content(project_root)
    except SyncError as error:
        assert "Unknown agent" in str(error)
    else:
        raise AssertionError("Expected SyncError for unsupported agent")


def test_chroma_feature_renders_usage_guidance(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)

    manifest = (
        MANIFEST_RELEASE_BLOCK
        + 'fragments = ["core/base"]\n'
        + 'features = ["chroma"]\n'
        + 'stacks = ["python"]\n'
        + 'local_overrides = ["docs/ai/project-rules.md"]\n'
        + "\n"
        + "[metadata]\n"
        + 'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )

    result = build_rendered_content(project_root)

    assert "## Chroma Usage" in result.content
    assert "freshness-gate wrapper" in result.content
    assert "atomic, resumable manifest" in result.content


def test_claude_and_kilo_are_accepted_agents(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)

    manifest = (
        MANIFEST_RELEASE_BLOCK
        + 'fragments = ["core/base"]\n'
        + 'features = ["chroma"]\n'
        + 'stacks = ["python"]\n'
        + 'local_overrides = ["docs/ai/project-rules.md"]\n'
        + "\n"
        + "[tooling]\n"
        + 'agents = ["codex", "claude", "kilo", "cursor"]\n'
        + "\n"
        + "[metadata]\n"
        + 'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )

    # Must not raise; claude and kilo are supported agents now.
    build_rendered_content(project_root)
    sync_project_templates(project_root)


def test_sync_creates_infra_and_skill_when_chroma_enabled(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)

    manifest = (
        MANIFEST_RELEASE_BLOCK
        + 'fragments = ["core/base", "core/architecture"]\n'
        + 'features = ["chroma"]\n'
        + 'stacks = ["python"]\n'
        + 'local_overrides = ["docs/ai/project-rules.md"]\n'
        + "\n"
        + "[tooling]\n"
        + 'agents = ["codex", "claude", "kilo", "cursor"]\n'
        + "\n"
        + "[metadata]\n"
        + 'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )

    results = sync_project_templates(project_root)
    statuses = [result.status for result in results]

    # One deploy-skill per declared agent (4), the always-deployed update skill
    # per declared agent (4), and 2 chroma infra templates.
    # simplify-review is gated on review-lenses, which this manifest does not enable.
    assert statuses.count("created") == 10
    assert (project_root / ".ai-standards" / "scripts" / "code_index.py").exists()
    assert (project_root / ".ai-standards" / "code-index.toml").exists()
    assert (
        project_root / ".codex/skills/ai-infrastructure/deploy-ai-knowledge-stack/SKILL.md"
    ).exists()
    assert (
        project_root / ".claude/commands/deploy-ai-knowledge-stack.md"
    ).exists()
    assert (
        project_root / ".agents/skills/ai-infrastructure/deploy-ai-knowledge-stack/SKILL.md"
    ).exists()
    assert (
        project_root / ".cursor/rules/deploy-ai-knowledge-stack.mdc"
    ).exists()
    assert not (project_root / ".claude/commands/simplify-review.md").exists()
    assert not (
        project_root / ".agents/skills/review-lenses/simplify-review/SKILL.md"
    ).exists()
    assert "Managed by ai-standards template:" in (
        project_root / ".ai-standards" / "scripts" / "code_index.py"
    ).read_text(encoding="utf-8")


def test_sync_deploys_standard_review_adapters_when_code_review_enabled(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)

    manifest = (
        MANIFEST_RELEASE_BLOCK
        + 'fragments = ["core/base", "core/architecture"]\n'
        + 'features = ["code-review"]\n'
        + 'stacks = ["python"]\n'
        + 'local_overrides = ["docs/ai/project-rules.md"]\n'
        + "\n"
        + "[tooling]\n"
        + 'agents = ["codex", "claude", "kilo", "cursor"]\n'
        + "\n"
        + "[metadata]\n"
        + 'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )

    results = sync_project_templates(project_root)

    # Declaring every agent hands the project the standard-review adapters for the
    # enabled code-review feature, the always-deployed update skill, and the
    # code-review report template.
    assert [result.destination_path.name for result in results] == [
        "SKILL.md",
        "SKILL.md",
        "standard-code-review.md",
        "update-ai-standards.md",
        "SKILL.md",
        "SKILL.md",
        "standard-code-review.mdc",
        "update-ai-standards.mdc",
        "code-review-report.md",
    ]
    for result in results:
        content = result.destination_path.read_text(encoding="utf-8")
        destination = result.destination_path.as_posix()
        if destination.endswith("code-review-report.md"):
            continue
        if "update-ai-standards" in destination:
            assert "update ai-standards" in content.lower(), result.destination_path
        else:
            assert "standard code review" in content, result.destination_path
    deployed = {result.destination_path.as_posix() for result in results}
    assert not any("simplify-review" in path for path in deployed)


def test_sync_deploys_update_skill_adapters_regardless_of_features(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)

    manifest = (
        MANIFEST_RELEASE_BLOCK
        + 'fragments = ["core/base"]\n'
        + 'features = ["conport"]\n'
        + 'stacks = ["python"]\n'
        + 'local_overrides = ["docs/ai/project-rules.md"]\n'
        + "\n"
        + "[tooling]\n"
        + 'agents = ["codex", "kilo"]\n'
        + "\n"
        + "[metadata]\n"
        + 'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )

    results = sync_project_templates(project_root)

    # The update skill maintains ai-standards itself, so it ships with any
    # deployment that declares agents, whatever features the manifest enables.
    assert [result.status for result in results] == ["created", "created"]
    for destination in (
        project_root / ".codex/skills/standards-update/update-ai-standards/SKILL.md",
        project_root / ".agents/skills/standards-update/update-ai-standards/SKILL.md",
    ):
        content = destination.read_text(encoding="utf-8")
        assert "update ai-standards" in content.lower(), destination
        assert "Never enable a feature without the user's explicit confirmation" in content


def test_check_fails_when_manifest_pin_drifts_from_the_source(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)

    manifest = (
        MANIFEST_RELEASE_BLOCK.replace(
            f'ai_standards_version = "{CURRENT_AI_STANDARDS_VERSION}"',
            'ai_standards_version = "0.0.1"',
        )
        + 'fragments = ["core/base"]\n'
        + 'features = ["conport"]\n'
        + 'stacks = ["python"]\n'
        + 'local_overrides = ["docs/ai/project-rules.md"]\n'
        + "\n"
        + "[metadata]\n"
        + 'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")

    with pytest.raises(SyncError) as excinfo:
        check(project_root=project_root)

    message = str(excinfo.value)
    assert "0.0.1" in message
    assert CURRENT_AI_STANDARDS_VERSION in message
    assert "update-ai-standards" in message


def test_render_warns_when_manifest_pin_drifts_from_the_source(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)

    manifest = (
        MANIFEST_RELEASE_BLOCK.replace(
            f'ai_standards_version = "{CURRENT_AI_STANDARDS_VERSION}"',
            'ai_standards_version = "0.0.1"',
        )
        + 'fragments = ["core/base"]\n'
        + 'features = ["conport"]\n'
        + 'stacks = ["python"]\n'
        + 'local_overrides = ["docs/ai/project-rules.md"]\n'
        + "\n"
        + "[metadata]\n"
        + 'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )

    render(project_root=project_root)

    output = capsys.readouterr().out
    assert "Warning:" in output
    assert "0.0.1" in output


def test_registry_feature_meta_references_known_features() -> None:
    registry = tomllib.loads((REPO_ROOT / "registry.toml").read_text(encoding="utf-8"))

    features = registry["features"]
    feature_meta = registry["feature_meta"]

    unknown = set(feature_meta) - set(features)
    assert not unknown, f"feature_meta names unknown features: {sorted(unknown)}"


def test_sync_deploys_code_review_report_template_without_any_agents(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)

    manifest = (
        MANIFEST_RELEASE_BLOCK
        + 'fragments = ["core/base", "core/architecture"]\n'
        + 'features = ["code-review"]\n'
        + 'stacks = ["python"]\n'
        + 'local_overrides = ["docs/ai/project-rules.md"]\n'
        + "\n"
        + "[tooling]\n"
        + "agents = []\n"
        + "\n"
        + "[metadata]\n"
        + 'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )

    results = sync_project_templates(project_root)

    # The report template is agent-agnostic: it lands even with no adapters declared.
    assert [result.status for result in results] == ["created"]
    report = project_root / ".ai-standards" / "code-review-report.md"
    assert report.exists()
    content = report.read_text(encoding="utf-8")
    assert "Managed by ai-standards template:" in content
    assert "### What Was Done" in content


def test_sync_skips_code_review_report_template_when_feature_disabled(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)

    manifest = (
        MANIFEST_RELEASE_BLOCK
        + 'fragments = ["core/base", "core/architecture"]\n'
        + 'features = ["review-lenses"]\n'
        + 'stacks = ["python"]\n'
        + 'local_overrides = ["docs/ai/project-rules.md"]\n'
        + "\n"
        + "[tooling]\n"
        + "agents = []\n"
        + "\n"
        + "[metadata]\n"
        + 'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )

    results = sync_project_templates(project_root)

    assert results == []
    assert not (project_root / ".ai-standards").exists()


def test_sync_skips_chroma_infra_when_feature_disabled(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "docs" / "ai").mkdir(parents=True)

    manifest = (
        MANIFEST_RELEASE_BLOCK
        + 'fragments = ["core/base", "core/architecture"]\n'
        + 'features = ["review-lenses"]\n'
        + 'stacks = ["python"]\n'
        + 'local_overrides = ["docs/ai/project-rules.md"]\n'
        + "\n"
        + "[tooling]\n"
        + 'agents = ["codex", "kilo"]\n'
        + "\n"
        + "[metadata]\n"
        + 'project_name = "demo-project"\n'
    )
    (project_root / "ai.project.toml").write_text(manifest, encoding="utf-8")
    (project_root / "docs" / "ai" / "project-rules.md").write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )

    results = sync_project_templates(project_root)

    # simplify-review for codex and kilo, plus the always-deployed update skill;
    # deploy skill and infra are gated.
    assert [result.status for result in results] == ["created"] * 4
    assert not (project_root / ".ai-standards").exists()
    assert not (project_root / ".codex" / "skills" / "ai-infrastructure").exists()


def _minimal_manifest(
    local_override: str,
    optional_override: str | None = None,
    features: str = "conport",
) -> str:
    manifest = (
        MANIFEST_RELEASE_BLOCK
        + 'fragments = ["core/base"]\n'
        + f'features = ["{features}"]\n'
        + 'stacks = ["python"]\n'
        + f'local_overrides = ["{local_override}"]\n'
    )
    if optional_override is not None:
        manifest += f'optional_local_overrides = ["{optional_override}"]\n'
    return manifest + "\n[metadata]\nproject_name = \"demo-project\"\n"


def test_strip_frontmatter_removes_only_a_leading_block() -> None:
    assert _strip_frontmatter("---\ntitle: x\n---\n# Heading\n") == "# Heading\n"
    assert _strip_frontmatter("# Heading\n\n---\n") == "# Heading\n\n---\n"


def test_strip_frontmatter_keeps_content_when_the_block_is_never_closed() -> None:
    unclosed = "---\nnot really frontmatter\n"

    assert _strip_frontmatter(unclosed) == unclosed


def test_local_override_frontmatter_does_not_reach_rendered_output(tmp_path: Path) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / "ai").mkdir(parents=True)
    (project_root / "ai.project.toml").write_text(
        _minimal_manifest("ai/project-rules.md", "ai/private-rules.local.md"),
        encoding="utf-8",
    )
    # An indexer that treats the file as a note stamps frontmatter onto it.
    (project_root / "ai" / "project-rules.md").write_text(
        "---\ntitle: project-rules\ntype: note\npermalink: demo/ai/project-rules\n---\n\n"
        "# Project-Specific AI Rules\n\n- Demo override.\n",
        encoding="utf-8",
    )
    (project_root / "ai" / "private-rules.local.md").write_text(
        "---\ntitle: private-rules\n---\n\n# Private Rules\n\n- Local only.\n",
        encoding="utf-8",
    )

    result = build_rendered_content(project_root)

    assert "permalink: demo/ai/project-rules" not in result.content
    assert "type: note" not in result.content
    assert "# Project-Specific AI Rules" in result.content
    assert "- Demo override." in result.content
    assert "# Private Rules" in result.content


def test_init_project_scaffolds_local_overrides_outside_the_knowledge_tree(
    tmp_path: Path,
) -> None:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()

    init_project(project_root)

    assert (project_root / "ai" / "project-rules.md").exists()
    assert not (project_root / "docs" / "ai" / "project-rules.md").exists()

    manifest = (project_root / "ai.project.toml").read_text(encoding="utf-8")
    assert '"ai/project-rules.md"' in manifest
    assert "docs/ai/project-rules.md" not in manifest

def _doctor_project(tmp_path: Path, override_path: str, features: str = "conport") -> Path:
    project_root = tmp_path / "demo-project"
    project_root.mkdir()
    (project_root / override_path).parent.mkdir(parents=True, exist_ok=True)
    (project_root / "ai.project.toml").write_text(
        _minimal_manifest(override_path, features=features), encoding="utf-8"
    )
    (project_root / override_path).write_text(
        "# Project-Specific AI Rules\n\n- Demo override.\n", encoding="utf-8"
    )
    return project_root


def _codes(report: DoctorReport) -> set[str]:
    return {finding.code for finding in report.findings}


def test_doctor_flags_a_rendering_input_inside_the_knowledge_tree(tmp_path: Path) -> None:
    project_root = _doctor_project(tmp_path, "docs/ai/project-rules.md")

    report = run_doctor(project_root)

    assert "override-inside-knowledge-tree" in _codes(report)
    assert report.error_count == 1


def test_doctor_accepts_a_rendering_input_outside_the_knowledge_tree(tmp_path: Path) -> None:
    project_root = _doctor_project(tmp_path, "ai/project-rules.md")

    report = run_doctor(project_root)

    assert "override-inside-knowledge-tree" not in _codes(report)
    assert report.error_count == 0


def test_doctor_flags_notes_whose_title_and_heading_disagree(tmp_path: Path) -> None:
    project_root = _doctor_project(tmp_path, "ai/project-rules.md")
    (project_root / "docs").mkdir()
    (project_root / "docs" / "note.md").write_text(
        "---\ntitle: Declared Title\n---\n\n# Different Heading\n\n"
        "## Observations\n- [fact] x\n\n## Relations\n- relates_to [[Other]]\n",
        encoding="utf-8",
    )

    report = run_doctor(project_root)

    assert "note-title-heading-mismatch" in _codes(report)
    assert report.notes_checked == 1


def test_doctor_reports_an_unreadable_note_instead_of_crashing(tmp_path: Path) -> None:
    project_root = _doctor_project(tmp_path, "ai/project-rules.md")
    (project_root / "docs").mkdir()
    (project_root / "docs" / "broken.md").write_bytes(b"# Title\n\xff\xfe not utf-8\n")

    report = run_doctor(project_root)

    assert "note-unreadable" in _codes(report)
    assert any(
        finding.severity == SEVERITY_ERROR and finding.code == "note-unreadable"
        for finding in report.findings
    )


def test_doctor_flags_an_indexer_project_pointed_at_the_repository_root(
    tmp_path: Path,
) -> None:
    project_root = _doctor_project(tmp_path, "ai/project-rules.md", features="basic-memory")
    (project_root / "docs").mkdir()
    indexer_config = tmp_path / "indexer.json"
    indexer_config.write_text(
        json.dumps({"projects": {"demo": {"path": str(project_root)}}}), encoding="utf-8"
    )

    report = run_doctor(project_root, indexer_config=indexer_config)

    assert "indexed-repository-root" in _codes(report)


def test_doctor_accepts_an_indexer_project_pointed_at_the_knowledge_tree(
    tmp_path: Path,
) -> None:
    project_root = _doctor_project(tmp_path, "ai/project-rules.md", features="basic-memory")
    (project_root / "docs").mkdir()
    indexer_config = tmp_path / "indexer.json"
    indexer_config.write_text(
        json.dumps({"projects": {"demo": {"path": str(project_root / "docs")}}}),
        encoding="utf-8",
    )

    report = run_doctor(project_root, indexer_config=indexer_config)

    assert "indexed-repository-root" not in _codes(report)
    assert "knowledge-tree-not-indexed" not in _codes(report)


def test_doctor_skips_indexer_checks_when_the_feature_is_disabled(tmp_path: Path) -> None:
    project_root = _doctor_project(tmp_path, "ai/project-rules.md")
    (project_root / "docs").mkdir()
    indexer_config = tmp_path / "indexer.json"
    indexer_config.write_text(
        json.dumps({"projects": {"demo": {"path": str(project_root)}}}), encoding="utf-8"
    )

    report = run_doctor(project_root, indexer_config=indexer_config)

    assert "indexed-repository-root" not in _codes(report)


def test_doctor_skips_the_archive_subtree(tmp_path: Path) -> None:
    project_root = _doctor_project(tmp_path, "ai/project-rules.md")
    _note(project_root, "docs/note.md", "---\ntitle: Note\n---\n\n# Note\n")
    _note(
        project_root,
        "docs/archive/20260101-log-old.md",
        "# Old Chat Log\n\nraw transcript prose nobody summarized into observations\n",
    )

    report = run_doctor(project_root)

    assert report.notes_checked == 1
    assert [f for f in report.findings if "docs/archive" in f.location] == []
    assert "note-without-frontmatter" not in _codes(report)


def test_doctor_flags_an_archive_missing_from_bmignore(tmp_path: Path) -> None:
    project_root = _doctor_project(tmp_path, "ai/project-rules.md", features="basic-memory")
    (project_root / "docs" / "archive").mkdir(parents=True)
    indexer_config = tmp_path / "indexer.json"
    indexer_config.write_text(
        json.dumps({"projects": {"demo": {"path": str(project_root / "docs")}}}),
        encoding="utf-8",
    )

    assert "archive-not-excluded" in _codes(run_doctor(project_root, indexer_config=indexer_config))


def test_doctor_accepts_archive_excluded_via_bmignore(tmp_path: Path) -> None:
    project_root = _doctor_project(tmp_path, "ai/project-rules.md", features="basic-memory")
    (project_root / "docs" / "archive").mkdir(parents=True)
    indexer_config = tmp_path / "indexer.json"
    indexer_config.write_text(
        json.dumps({"projects": {"demo": {"path": str(project_root / "docs")}}}),
        encoding="utf-8",
    )
    (indexer_config.parent / ".bmignore").write_text("*.tmp\narchive/\n", encoding="utf-8")

    report = run_doctor(project_root, indexer_config=indexer_config)

    assert "archive-not-excluded" not in _codes(report)


def _note(project_root: Path, relative_path: str, content: str) -> Path:
    note_path = project_root / relative_path
    note_path.parent.mkdir(parents=True, exist_ok=True)
    note_path.write_text(content, encoding="utf-8")
    return note_path


def test_doctor_flags_a_file_name_against_the_convention(tmp_path: Path) -> None:
    project_root = _doctor_project(tmp_path, "ai/project-rules.md")
    _note(project_root, "docs/decisions/2026-08-20 Решение — брокер очередей.md", "# x\n")

    assert "note-name-against-convention" in _codes(run_doctor(project_root))


def test_doctor_accepts_a_dated_ascii_slug(tmp_path: Path) -> None:
    project_root = _doctor_project(tmp_path, "ai/project-rules.md")
    _note(project_root, "docs/decisions/2026-08-20-queue-broker-choice.md", "# x\n")
    _note(project_root, "docs/README.md", "# x\n")

    assert "note-name-against-convention" not in _codes(run_doctor(project_root))


def test_fix_moves_a_rendering_input_out_of_the_tree(tmp_path: Path) -> None:
    project_root = _doctor_project(tmp_path, "docs/ai/project-rules.md")

    run_repair(project_root, run_doctor(project_root))

    assert (project_root / "ai" / "project-rules.md").exists()
    assert not (project_root / "docs" / "ai").exists()
    manifest = (project_root / "ai.project.toml").read_text(encoding="utf-8")
    assert '"ai/project-rules.md"' in manifest
    assert run_doctor(project_root).error_count == 0


def test_fix_restores_a_missing_frontmatter_title(tmp_path: Path) -> None:
    project_root = _doctor_project(tmp_path, "ai/project-rules.md")
    note = _note(project_root, "docs/note.md", "# Real Heading\n\nbody\n")

    run_repair(project_root, run_doctor(project_root))

    content = note.read_text(encoding="utf-8")
    assert content.startswith("---\ntitle: Real Heading\n---\n")
    assert "# Real Heading" in content
    assert "note-without-frontmatter" not in _codes(run_doctor(project_root))


def test_fix_aligns_the_heading_with_the_frontmatter_title(tmp_path: Path) -> None:
    project_root = _doctor_project(tmp_path, "ai/project-rules.md")
    note = _note(
        project_root, "docs/note.md", "---\ntitle: Declared\n---\n\n# Drifted\n\nbody\n"
    )

    run_repair(project_root, run_doctor(project_root))

    assert "# Declared" in note.read_text(encoding="utf-8")
    assert "note-title-heading-mismatch" not in _codes(run_doctor(project_root))


def test_fix_inserts_a_missing_heading(tmp_path: Path) -> None:
    project_root = _doctor_project(tmp_path, "ai/project-rules.md")
    note = _note(project_root, "docs/note.md", "---\ntitle: Declared\n---\n\nbody only\n")

    run_repair(project_root, run_doctor(project_root))

    content = note.read_text(encoding="utf-8")
    assert "# Declared" in content
    assert "body only" in content


def test_fix_prunes_directories_it_empties(tmp_path: Path) -> None:
    project_root = _doctor_project(tmp_path, "ai/project-rules.md")
    (project_root / "docs" / "empty").mkdir(parents=True)

    actions = run_repair(project_root, run_doctor(project_root))

    assert not (project_root / "docs" / "empty").exists()
    assert any(action.code == "empty-directory" for action in actions)


def test_fix_leaves_naming_and_content_findings_alone(tmp_path: Path) -> None:
    project_root = _doctor_project(tmp_path, "ai/project-rules.md")
    note = _note(
        project_root,
        "docs/decisions/Плохое Имя.md",
        "---\ntitle: Плохое Имя\n---\n\n# Плохое Имя\n",
    )

    run_repair(project_root, run_doctor(project_root))

    assert note.exists(), "renaming needs a meaningful slug, so it must not be automated"
    remaining = _codes(run_doctor(project_root))
    assert "note-name-against-convention" in remaining
    assert "note-without-observations" in remaining


def test_doctor_leaves_names_alone_outside_the_governed_directories(tmp_path: Path) -> None:
    project_root = _doctor_project(tmp_path, "ai/project-rules.md")
    # Living documents and working memory are not canonical dated artifacts, and neither
    # are conventional files a project is required to name a particular way.
    _note(project_root, "docs/ai-memory/Статус проекта.md", "# Статус проекта\n")
    _note(project_root, "docs/MODULE_CONTRACT.md", "# MODULE_CONTRACT\n")

    assert "note-name-against-convention" not in _codes(run_doctor(project_root))


def test_manifest_can_redeclare_the_governed_directories(tmp_path: Path) -> None:
    project_root = _doctor_project(tmp_path, "ai/project-rules.md")
    manifest = project_root / "ai.project.toml"
    manifest.write_text(
        manifest.read_text(encoding="utf-8")
        + '\n[basic_memory]\ndated_note_directories = ["reports"]\n',
        encoding="utf-8",
    )
    _note(project_root, "docs/reports/Плохое Имя.md", "# Плохое Имя\n")
    _note(project_root, "docs/decisions/Тоже Плохое.md", "# Тоже Плохое\n")

    locations = {
        finding.location
        for finding in run_doctor(project_root).findings
        if finding.code == "note-name-against-convention"
    }

    assert locations == {"docs/reports/Плохое Имя.md"}


def test_manifest_can_redeclare_the_knowledge_tree(tmp_path: Path) -> None:
    project_root = _doctor_project(tmp_path, "ai/project-rules.md")
    manifest = project_root / "ai.project.toml"
    manifest.write_text(
        manifest.read_text(encoding="utf-8") + '\n[basic_memory]\nknowledge_tree = "knowledge"\n',
        encoding="utf-8",
    )
    _note(project_root, "knowledge/note.md", "---\ntitle: Note\n---\n\n# Note\n")

    report = run_doctor(project_root)

    assert report.knowledge_tree.name == "knowledge"
    assert report.notes_checked == 1


def test_fix_aligns_the_first_level_heading_not_a_deeper_one_that_matches(
    tmp_path: Path,
) -> None:
    project_root = _doctor_project(tmp_path, "ai/project-rules.md")
    note = _note(
        project_root,
        "docs/note.md",
        "---\ntitle: Declared\n---\n\n## Drifted\n\ntext\n\n# Drifted\n\nbody\n",
    )

    run_repair(project_root, run_doctor(project_root))

    content = note.read_text(encoding="utf-8")
    assert "## Drifted" in content, "a deeper heading must survive untouched"
    assert "# Declared\n" in content
    assert "note-title-heading-mismatch" not in _codes(run_doctor(project_root))


def test_fix_moves_nothing_when_the_manifest_cannot_be_repointed(tmp_path: Path) -> None:
    project_root = _doctor_project(tmp_path, "docs/ai/project-rules.md")
    manifest = project_root / "ai.project.toml"
    # Valid TOML that the textual repoint cannot match.
    manifest.write_text(
        manifest.read_text(encoding="utf-8").replace(
            '"docs/ai/project-rules.md"', "'docs/ai/project-rules.md'"
        ),
        encoding="utf-8",
    )

    with pytest.raises(SyncError):
        run_repair(project_root, run_doctor(project_root))

    assert (project_root / "docs" / "ai" / "project-rules.md").exists()
    assert not (project_root / "ai" / "project-rules.md").exists()
    assert "'docs/ai/project-rules.md'" in manifest.read_text(encoding="utf-8")
    # The project still renders from its declared path.
    assert build_rendered_content(project_root).content


def test_doctor_accepts_a_localized_sibling_of_a_well_named_note(tmp_path: Path) -> None:
    project_root = _doctor_project(tmp_path, "ai/project-rules.md")
    _note(project_root, "docs/decisions/2026-08-20-queue-broker-choice.md", "# x\n")
    _note(project_root, "docs/decisions/2026-08-20-queue-broker-choice.ru.md", "# x\n")

    assert "note-name-against-convention" not in _codes(run_doctor(project_root))


def test_doctor_accepts_a_relative_project_root(tmp_path: Path, monkeypatch) -> None:  # type: ignore[no-untyped-def]
    project_root = _doctor_project(tmp_path, "ai/project-rules.md")
    _note(project_root, "docs/note.md", "---\ntitle: Note\n---\n\n# Note\n")
    monkeypatch.chdir(project_root)

    report = run_doctor(Path("."))

    assert report.notes_checked == 1


def test_fix_quotes_a_title_that_would_break_yaml(tmp_path: Path) -> None:
    project_root = _doctor_project(tmp_path, "ai/project-rules.md")
    note = _note(project_root, "docs/note.md", "# DECISION: add-basic-memory-feature\n\nbody\n")

    run_repair(project_root, run_doctor(project_root))

    content = note.read_text(encoding="utf-8")
    assert 'title: "DECISION: add-basic-memory-feature"' in content
    # And the value survives a round trip through the reader.
    assert "note-title-heading-mismatch" not in _codes(run_doctor(project_root))
    assert "note-without-title" not in _codes(run_doctor(project_root))


def test_doctor_counts_observations_and_relations_by_syntax_not_by_heading(
    tmp_path: Path,
) -> None:
    project_root = _doctor_project(tmp_path, "ai/project-rules.md")
    _note(
        project_root,
        "docs/note.md",
        "---\ntitle: Note\n---\n\n# Note\n\n- [decision] Chose one thing over another\n\n"
        "Related work lives in [[Other Note]].\n",
    )

    codes = _codes(run_doctor(project_root))

    assert "note-without-observations" not in codes
    assert "note-without-relations" not in codes


def test_doctor_does_not_mistake_a_markdown_link_for_an_observation(tmp_path: Path) -> None:
    project_root = _doctor_project(tmp_path, "ai/project-rules.md")
    _note(
        project_root,
        "docs/note.md",
        "---\ntitle: Note\n---\n\n# Note\n\n- [see the guide](guide.md)\n",
    )

    assert "note-without-observations" in _codes(run_doctor(project_root))


def test_the_problem_space_tree_is_governed_by_default(tmp_path: Path) -> None:
    project_root = _doctor_project(tmp_path, "ai/project-rules.md")
    _note(project_root, "docs/domain/Плохое Имя.md", "# Плохое Имя\n")
    _note(project_root, "docs/domain/2026-08-20-sick-leave-rounding.md", "# x\n")

    locations = {
        finding.location
        for finding in run_doctor(project_root).findings
        if finding.code == "note-name-against-convention"
    }

    assert locations == {"docs/domain/Плохое Имя.md"}


def test_doctor_names_the_other_roots_that_block_a_global_setting(tmp_path: Path) -> None:
    project_root = _doctor_project(tmp_path, "ai/project-rules.md", features="basic-memory")
    (project_root / "docs").mkdir()
    other = tmp_path / "other-repo"
    (other / ".git").mkdir(parents=True)
    # A workspace umbrella gives itself away the same way, without being a repository.
    umbrella = tmp_path / "umbrella"
    umbrella.mkdir()
    (umbrella / "Makefile").write_text("all:\n", encoding="utf-8")
    indexer_config = tmp_path / "indexer.json"
    indexer_config.write_text(
        json.dumps(
            {
                "projects": {
                    "demo": {"path": str(project_root / "docs")},
                    "other": {"path": str(other)},
                    "umbrella": {"path": str(umbrella)},
                },
                "disable_permalinks": True,
            }
        ),
        encoding="utf-8",
    )

    findings = run_doctor(project_root, indexer_config=indexer_config).findings
    by_code = {finding.code: finding for finding in findings}

    assert "other-indexed-repository-roots" in by_code
    assert "other" in by_code["other-indexed-repository-roots"].message
    assert "umbrella" in by_code["other-indexed-repository-roots"].message
    # The blocked setting points at the finding that explains why it is blocked.
    assert "other-indexed-repository-roots" in by_code["permalinks-disabled"].message


def test_doctor_stays_quiet_when_every_other_root_is_a_knowledge_tree(tmp_path: Path) -> None:
    project_root = _doctor_project(tmp_path, "ai/project-rules.md", features="basic-memory")
    (project_root / "docs").mkdir()
    other_tree = tmp_path / "other-repo" / "docs"
    other_tree.mkdir(parents=True)
    indexer_config = tmp_path / "indexer.json"
    indexer_config.write_text(
        json.dumps(
            {
                "projects": {
                    "demo": {"path": str(project_root / "docs")},
                    "other": {"path": str(other_tree)},
                }
            }
        ),
        encoding="utf-8",
    )

    codes = _codes(run_doctor(project_root, indexer_config=indexer_config))

    assert "other-indexed-repository-roots" not in codes


def test_doctor_does_not_list_this_project_among_the_blocking_roots(tmp_path: Path) -> None:
    project_root = _doctor_project(tmp_path, "ai/project-rules.md", features="basic-memory")
    (project_root / "docs").mkdir()
    indexer_config = tmp_path / "indexer.json"
    indexer_config.write_text(
        json.dumps({"projects": {"demo": {"path": str(project_root)}}, "disable_permalinks": True}),
        encoding="utf-8",
    )

    codes = _codes(run_doctor(project_root, indexer_config=indexer_config))

    # Its own root is already reported as indexed-repository-root.
    assert "indexed-repository-root" in codes
    assert "other-indexed-repository-roots" not in codes


def test_fix_strips_frontmatter_an_indexer_left_on_a_rendering_input(tmp_path: Path) -> None:
    project_root = _doctor_project(tmp_path, "docs/ai/project-rules.md")
    stamped = project_root / "docs" / "ai" / "project-rules.md"
    stamped.write_text(
        "---\ntitle: project-rules\n---\n\n# Project-Specific AI Rules\n", encoding="utf-8"
    )

    run_repair(project_root, run_doctor(project_root))

    moved = project_root / "ai" / "project-rules.md"
    assert moved.read_text(encoding="utf-8").startswith("# Project-Specific AI Rules")
    assert "override-carries-frontmatter" not in _codes(run_doctor(project_root))


def test_dry_pass_reaches_the_fragment_and_every_simplify_review_adapter() -> None:
    """Guard the propagation, not the wording.

    Each `simplify-review` adapter restates the workflow in its own voice rather than
    copying the fragment, so the four texts cannot be compared to each other. What must
    not happen is an adapter losing the `DRY` pass entirely while the fragment keeps it.
    """
    surfaces = [
        REPO_ROOT / "fragments" / "process" / "review-lenses.md",
        REPO_ROOT / "templates" / "review-lenses" / "simplify-review.SKILL.md",
        REPO_ROOT / "templates" / "review-lenses" / "simplify-review.claude.md",
        REPO_ROOT / "templates" / "review-lenses" / "simplify-review.cursor.mdc",
    ]

    for surface in surfaces:
        headings = [
            line.lstrip("#").strip()
            for line in surface.read_text(encoding="utf-8").splitlines()
            if line.startswith("#")
        ]
        assert "DRY" in headings, f"{surface.name} has no DRY section"
