from __future__ import annotations

import json
import re
import tomllib
from dataclasses import dataclass
from pathlib import Path
from typing import Annotated, cast

import typer

MANIFEST_FILE_NAME = "ai.project.toml"
GENERATED_MARKER = "Generated by ai-standards"
DEFAULT_OUTPUT_NAME = "AGENTS.md"
CLAUDE_BRIDGE_FILE = "CLAUDE.md"
CLAUDE_BRIDGE_MARKER = "Managed by ai-standards: claude-bridge"
MANAGED_TEMPLATE_MARKER_PREFIX = "Managed by ai-standards template:"
FRONTMATTER_DELIMITER = "---\n"
DEFAULT_KNOWLEDGE_TREE = "docs"
DEFAULT_INDEXER_CONFIG = Path.home() / ".basic-memory" / "config.json"
ARCHIVE_DIRECTORY_NAME = "archive"
SEVERITY_ERROR = "error"
SEVERITY_WARNING = "warning"
# A canonical note file name: a lowercase ASCII slug, optionally date-prefixed.
NOTE_NAME_PATTERN = re.compile(r"^(\d{4}-\d{2}-\d{2}-)?[a-z0-9]+(-[a-z0-9]+)*$")
# The convention claims canonical notes only. Everything else in the tree — living
# documents, working memory, conventional files like MODULE_CONTRACT.md — is out of scope.
DEFAULT_DATED_NOTE_DIRECTORIES = ("domain", "decisions", "architecture")
# A localized sibling such as `<name>.ru.md` keeps the base name, so the language tag is
# stripped before the name is judged.
LANGUAGE_SUFFIX_PATTERN = re.compile(r"\.[a-z]{2}$")
# An observation is `- [category] text`; the negative lookahead keeps ordinary markdown
# links such as `- [label](url)` from counting as one.
OBSERVATION_PATTERN = re.compile(r"^\s*[-*]\s*\[[^\]]+\](?!\()", re.MULTILINE)
# A relation is any wiki link, wherever it appears — a `## Relations` section is a
# convention for grouping them, not what makes them relations.
RELATION_PATTERN = re.compile(r"\[\[[^\]]+\]\]")
DEFAULT_OVERRIDE_DIRECTORY = "ai"
PROJECT_ROOT_OPTION = typer.Option(..., exists=True, file_okay=False, resolve_path=True)
OUTPUT_NAME_OPTION: object = typer.Option(...)

app = typer.Typer(add_completion=False, no_args_is_help=True)


class SyncError(RuntimeError):
    """Raised when AI standards rendering cannot continue safely."""


@dataclass(frozen=True)
class Registry:
    features: dict[str, list[str]]
    stacks: dict[str, list[str]]


@dataclass(frozen=True)
class Manifest:
    ai_standards_version: str
    project_version: str | None
    project_release_date: str | None
    fragments: list[str]
    features: list[str]
    stacks: list[str]
    local_overrides: list[str]
    optional_local_overrides: list[str]
    agents: list[str]
    metadata: dict[str, str]
    knowledge_tree: str | None
    dated_note_directories: list[str] | None


@dataclass(frozen=True)
class RenderResult:
    project_root: Path
    output_path: Path
    content: str
    fragment_ids: list[str]


@dataclass(frozen=True)
class AgentTemplate:
    agent: str
    source_relative_path: str
    destination_relative_path: str
    feature: str | None = None


@dataclass(frozen=True)
class TemplateSyncResult:
    status: str
    destination_path: Path


@dataclass(frozen=True)
class ReleaseMetadata:
    version: str
    release_date: str


AGENT_TEMPLATES: dict[str, tuple[AgentTemplate, ...]] = {
    "codex": (
        AgentTemplate(
            agent="codex",
            source_relative_path="templates/review-lenses/simplify-review.SKILL.md",
            destination_relative_path=".codex/skills/review-lenses/simplify-review/SKILL.md",
            feature="review-lenses",
        ),
        AgentTemplate(
            agent="codex",
            source_relative_path="templates/ai-infrastructure/deploy-ai-knowledge-stack.SKILL.md",
            destination_relative_path=".codex/skills/ai-infrastructure/deploy-ai-knowledge-stack/SKILL.md",
            feature="chroma",
        ),
        AgentTemplate(
            agent="codex",
            source_relative_path="templates/knowledge-tree/audit-knowledge-tree.SKILL.md",
            destination_relative_path=".codex/skills/knowledge-tree/audit-knowledge-tree/SKILL.md",
            feature="basic-memory",
        ),
    ),
    "cursor": (
        AgentTemplate(
            agent="cursor",
            source_relative_path="templates/review-lenses/simplify-review.cursor.mdc",
            destination_relative_path=".cursor/rules/simplify-review.mdc",
            feature="review-lenses",
        ),
        AgentTemplate(
            agent="cursor",
            source_relative_path="templates/ai-infrastructure/deploy-ai-knowledge-stack.cursor.mdc",
            destination_relative_path=".cursor/rules/deploy-ai-knowledge-stack.mdc",
            feature="chroma",
        ),
        AgentTemplate(
            agent="cursor",
            source_relative_path="templates/knowledge-tree/audit-knowledge-tree.cursor.mdc",
            destination_relative_path=".cursor/rules/audit-knowledge-tree.mdc",
            feature="basic-memory",
        ),
    ),
    "claude": (
        AgentTemplate(
            agent="claude",
            source_relative_path="templates/review-lenses/simplify-review.claude.md",
            destination_relative_path=".claude/commands/simplify-review.md",
            feature="review-lenses",
        ),
        AgentTemplate(
            agent="claude",
            source_relative_path="templates/ai-infrastructure/deploy-ai-knowledge-stack.claude.md",
            destination_relative_path=".claude/commands/deploy-ai-knowledge-stack.md",
            feature="chroma",
        ),
        AgentTemplate(
            agent="claude",
            source_relative_path="templates/knowledge-tree/audit-knowledge-tree.claude.md",
            destination_relative_path=".claude/commands/audit-knowledge-tree.md",
            feature="basic-memory",
        ),
    ),
    "kilo": (
        AgentTemplate(
            agent="kilo",
            source_relative_path="templates/review-lenses/simplify-review.SKILL.md",
            destination_relative_path=".agents/skills/review-lenses/simplify-review/SKILL.md",
            feature="review-lenses",
        ),
        AgentTemplate(
            agent="kilo",
            source_relative_path="templates/ai-infrastructure/deploy-ai-knowledge-stack.SKILL.md",
            destination_relative_path=".agents/skills/ai-infrastructure/deploy-ai-knowledge-stack/SKILL.md",
            feature="chroma",
        ),
        AgentTemplate(
            agent="kilo",
            source_relative_path="templates/knowledge-tree/audit-knowledge-tree.SKILL.md",
            destination_relative_path=".agents/skills/knowledge-tree/audit-knowledge-tree/SKILL.md",
            feature="basic-memory",
        ),
    ),
}

# Agent-agnostic infrastructure templates, synced once per project (not per
# agent). Each is gated by a feature, so it is materialized only when the
# manifest enables that feature. The ``agent`` field is unused for sync.
INFRA_TEMPLATES: tuple[AgentTemplate, ...] = (
    AgentTemplate(
        agent="",
        source_relative_path="templates/ai-infrastructure/scripts/code_index.py",
        destination_relative_path=".ai-standards/scripts/code_index.py",
        feature="chroma",
    ),
    AgentTemplate(
        agent="",
        source_relative_path="templates/ai-infrastructure/code-index.toml",
        destination_relative_path=".ai-standards/code-index.toml",
        feature="chroma",
    ),
    AgentTemplate(
        agent="",
        source_relative_path="templates/code-review-report.md",
        destination_relative_path=".ai-standards/code-review-report.md",
        feature="code-review",
    ),
)


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def _load_toml(path: Path) -> dict[str, object]:
    if not path.exists():
        raise SyncError(f"Required file does not exist: {path}")
    try:
        loaded = cast(dict[str, object], tomllib.loads(path.read_text(encoding="utf-8")))
    except tomllib.TOMLDecodeError as error:
        raise SyncError(f"Invalid TOML in {path}: {error}") from error
    return loaded


def _load_registry(repo_root: Path) -> Registry:
    data = _load_toml(repo_root / "registry.toml")
    features = _expect_mapping_of_string_lists(data, "features", "registry")
    stacks = _expect_mapping_of_string_lists(data, "stacks", "registry")
    return Registry(features=features, stacks=stacks)


def _load_release_metadata(repo_root: Path) -> ReleaseMetadata:
    data = _load_toml(repo_root / "pyproject.toml")
    tool = _expect_optional_table(data, "tool", "pyproject")
    ai_standards_tool = _expect_optional_table(tool, "ai-standards", "pyproject.tool")
    return ReleaseMetadata(
        version=_expect_string(
            ai_standards_tool,
            "version",
            "pyproject.tool.ai-standards",
        ),
        release_date=_expect_string(
            ai_standards_tool,
            "release_date",
            "pyproject.tool.ai-standards",
        ),
    )


def _load_manifest(project_root: Path) -> Manifest:
    data = _load_toml(project_root / MANIFEST_FILE_NAME)
    metadata_raw = _expect_optional_table(data, "metadata", "manifest")
    tooling_raw = _expect_optional_table(data, "tooling", "manifest")
    knowledge_raw = _expect_optional_table(data, "basic_memory", "manifest")
    metadata: dict[str, str] = {}
    for key, value in metadata_raw.items():
        if not isinstance(value, str):
            raise SyncError("All metadata values must be strings")
        metadata[key] = value

    return Manifest(
        ai_standards_version=_expect_string_alias(
            data,
            primary_key="ai_standards_version",
            fallback_key="version",
            context="manifest",
        ),
        project_version=_expect_optional_string(data, "project_version", "manifest"),
        project_release_date=_expect_optional_string(
            data,
            "project_release_date",
            "manifest",
        ),
        fragments=_expect_string_list(data, "fragments", "manifest"),
        features=_expect_string_list(data, "features", "manifest"),
        stacks=_expect_string_list(data, "stacks", "manifest"),
        local_overrides=_expect_string_list(data, "local_overrides", "manifest"),
        optional_local_overrides=_expect_optional_string_list(
            data,
            "optional_local_overrides",
            "manifest",
        ),
        agents=_expect_supported_agents(tooling_raw, "agents", "manifest.tooling"),
        metadata=metadata,
        knowledge_tree=_expect_optional_string(
            knowledge_raw,
            "knowledge_tree",
            "manifest.basic_memory",
        ),
        dated_note_directories=(
            _expect_optional_string_list(
                knowledge_raw,
                "dated_note_directories",
                "manifest.basic_memory",
            )
            if "dated_note_directories" in knowledge_raw
            else None
        ),
    )


def _expect_string(data: dict[str, object], key: str, context: str) -> str:
    value = data.get(key)
    if not isinstance(value, str) or not value:
        raise SyncError(f"Expected non-empty string '{key}' in {context}")
    return value


def _expect_optional_string(data: dict[str, object], key: str, context: str) -> str | None:
    value = data.get(key)
    if value is None:
        return None
    if not isinstance(value, str) or not value:
        raise SyncError(f"Expected non-empty string '{key}' in {context}")
    return value


def _expect_string_alias(
    data: dict[str, object],
    primary_key: str,
    fallback_key: str,
    context: str,
) -> str:
    primary_value = data.get(primary_key)
    if primary_value is not None:
        if not isinstance(primary_value, str) or not primary_value:
            raise SyncError(f"Expected non-empty string '{primary_key}' in {context}")
        return primary_value
    return _expect_string(data, fallback_key, context)


def _expect_string_list(data: dict[str, object], key: str, context: str) -> list[str]:
    value = data.get(key)
    if not isinstance(value, list) or not value:
        raise SyncError(f"Expected non-empty list '{key}' in {context}")
    if not all(isinstance(item, str) and item for item in value):
        raise SyncError(f"Every item in '{key}' in {context} must be a non-empty string")
    return list(value)


def _expect_optional_string_list(data: dict[str, object], key: str, context: str) -> list[str]:
    value = data.get(key, [])
    if not isinstance(value, list):
        raise SyncError(f"Expected list '{key}' in {context}")
    if not all(isinstance(item, str) and item for item in value):
        raise SyncError(f"Every item in '{key}' in {context} must be a non-empty string")
    return list(value)


def _expect_supported_agents(data: dict[str, object], key: str, context: str) -> list[str]:
    values = _expect_optional_string_list(data, key, context)
    invalid = sorted({value for value in values if value not in AGENT_TEMPLATES})
    if invalid:
        supported = ", ".join(sorted(AGENT_TEMPLATES))
        invalid_text = ", ".join(invalid)
        raise SyncError(f"Unknown agent '{invalid_text}' in {context}; supported: {supported}")
    return values


def _expect_optional_table(
    data: dict[str, object],
    key: str,
    context: str,
) -> dict[str, object]:
    value = data.get(key, {})
    if not isinstance(value, dict):
        raise SyncError(f"Expected table '{key}' in {context}")

    result: dict[str, object] = {}
    for mapping_key, mapping_value in value.items():
        if not isinstance(mapping_key, str):
            raise SyncError(f"Expected string key inside '{key}' in {context}")
        result[mapping_key] = mapping_value
    return result


def _expect_mapping_of_string_lists(
    data: dict[str, object],
    key: str,
    context: str,
) -> dict[str, list[str]]:
    value = _expect_optional_table(data, key, context)
    result: dict[str, list[str]] = {}
    for mapping_key, mapping_value in value.items():
        if not isinstance(mapping_value, list) or not mapping_value:
            raise SyncError(
                f"Expected non-empty list for '{mapping_key}' inside '{key}' in {context}"
            )
        if not all(isinstance(item, str) and item for item in mapping_value):
            raise SyncError(
                f"Every fragment id for '{mapping_key}' inside '{key}' in {context} "
                "must be a string"
            )
        result[mapping_key] = list(mapping_value)
    return result


def _resolve_fragment_ids(manifest: Manifest, registry: Registry) -> list[str]:
    resolved: list[str] = []
    seen: set[str] = set()

    for fragment_id in manifest.fragments:
        _append_fragment_id(resolved, seen, fragment_id)

    for feature_name in manifest.features:
        if feature_name not in registry.features:
            raise SyncError(f"Unknown feature '{feature_name}' in {MANIFEST_FILE_NAME}")
        for fragment_id in registry.features[feature_name]:
            _append_fragment_id(resolved, seen, fragment_id)

    for stack_name in manifest.stacks:
        if stack_name not in registry.stacks:
            raise SyncError(f"Unknown stack '{stack_name}' in {MANIFEST_FILE_NAME}")
        for fragment_id in registry.stacks[stack_name]:
            _append_fragment_id(resolved, seen, fragment_id)

    return resolved


def _append_fragment_id(resolved: list[str], seen: set[str], fragment_id: str) -> None:
    if fragment_id not in seen:
        resolved.append(fragment_id)
        seen.add(fragment_id)


def _split_frontmatter(raw_content: str) -> tuple[str | None, str]:
    """Split Markdown into its leading frontmatter block and the body after it.

    Returns ``(None, raw_content)`` when the text carries no frontmatter, so callers can
    distinguish "absent" from "present but empty".
    """
    if not raw_content.startswith(FRONTMATTER_DELIMITER):
        return None, raw_content
    closing_index = raw_content.find(
        f"\n{FRONTMATTER_DELIMITER}", len(FRONTMATTER_DELIMITER)
    )
    if closing_index == -1:
        return None, raw_content
    block = raw_content[len(FRONTMATTER_DELIMITER) : closing_index + 1]
    body = raw_content[closing_index + len(f"\n{FRONTMATTER_DELIMITER}") :]
    return block, body


def _strip_frontmatter(raw_content: str) -> str:
    """Drop a leading YAML frontmatter block from a rendering input.

    Knowledge-base indexers may add frontmatter to Markdown they index. Fragments and
    local overrides are concatenated verbatim into the generated file, so that metadata
    would otherwise surface in the middle of the rendered output.
    """
    return _split_frontmatter(raw_content)[1]


def _read_fragment(repo_root: Path, fragment_id: str) -> str:
    fragment_path = repo_root / "fragments" / f"{fragment_id}.md"
    if not fragment_path.exists():
        raise SyncError(f"Fragment does not exist: {fragment_path}")
    return _strip_frontmatter(fragment_path.read_text(encoding="utf-8")).strip()


def _read_override(project_root: Path, relative_path: str) -> str:
    override_path = project_root / relative_path
    if not override_path.exists():
        raise SyncError(f"Local override does not exist: {override_path}")
    return _strip_frontmatter(override_path.read_text(encoding="utf-8")).strip()


def _read_optional_override(project_root: Path, relative_path: str) -> str | None:
    override_path = project_root / relative_path
    if not override_path.exists():
        return None
    return _strip_frontmatter(override_path.read_text(encoding="utf-8")).strip()


def build_rendered_content(
    project_root: Path,
    output_name: str = DEFAULT_OUTPUT_NAME,
    repo_root: Path | None = None,
) -> RenderResult:
    effective_repo_root = _repo_root() if repo_root is None else repo_root
    registry = _load_registry(effective_repo_root)
    release_metadata = _load_release_metadata(effective_repo_root)
    manifest = _load_manifest(project_root)
    fragment_ids = _resolve_fragment_ids(manifest, registry)

    sections: list[str] = []
    for fragment_id in fragment_ids:
        sections.append(_read_fragment(effective_repo_root, fragment_id))

    for relative_path in manifest.local_overrides:
        sections.append(_read_override(project_root, relative_path))

    for relative_path in manifest.optional_local_overrides:
        optional_content = _read_optional_override(project_root, relative_path)
        if optional_content is not None:
            sections.append(optional_content)

    metadata_lines = [
        (
            f"<!-- {GENERATED_MARKER} v{release_metadata.version} "
            f"release date: {release_metadata.release_date}. Do not edit manually. -->"
        ),
        f"<!-- Fragments: {', '.join(fragment_ids)} -->",
    ]
    if manifest.ai_standards_version != release_metadata.version:
        metadata_lines.append(
            f"<!-- Requested ai-standards version: {manifest.ai_standards_version} -->"
        )
    if manifest.project_version and manifest.project_release_date:
        metadata_lines.append(
            f"<!-- Project version: {manifest.project_version} "
            f"release date: {manifest.project_release_date} -->"
        )
    elif manifest.project_version:
        metadata_lines.append(f"<!-- Project version: {manifest.project_version} -->")
    elif manifest.project_release_date:
        metadata_lines.append(
            f"<!-- Project release date: {manifest.project_release_date} -->"
        )
    if manifest.metadata:
        for key in sorted(manifest.metadata):
            metadata_lines.append(f"<!-- Metadata {key}: {manifest.metadata[key]} -->")

    content = "\n\n".join(metadata_lines + ["\n".join(sections)]).strip() + "\n"
    return RenderResult(
        project_root=project_root,
        output_path=project_root / output_name,
        content=content,
        fragment_ids=fragment_ids,
    )


def write_rendered_content(result: RenderResult) -> None:
    result.output_path.write_text(result.content, encoding="utf-8")


def ensure_generated_file(result: RenderResult) -> None:
    if not result.output_path.exists():
        raise SyncError(f"Generated file does not exist: {result.output_path}")

    existing = result.output_path.read_text(encoding="utf-8")
    if GENERATED_MARKER not in existing:
        raise SyncError(
            f"{result.output_path} exists but is not marked as generated by ai-standards"
        )


def _copy_template_if_missing(source_path: Path, destination_path: Path) -> bool:
    if destination_path.exists():
        return False
    destination_path.parent.mkdir(parents=True, exist_ok=True)
    destination_path.write_text(source_path.read_text(encoding="utf-8"), encoding="utf-8")
    return True


def _seed_manifest_release_version(project_root: Path) -> None:
    release_metadata = _load_release_metadata(_repo_root())
    manifest_path = project_root / MANIFEST_FILE_NAME
    content = manifest_path.read_text(encoding="utf-8")
    content = content.replace(
        'ai_standards_version = "replace-me"',
        f'ai_standards_version = "{release_metadata.version}"',
        1,
    )
    manifest_path.write_text(content, encoding="utf-8")


HTML_MARKER_SUFFIXES = frozenset({".md", ".mdc", ".html"})


def _build_managed_marker(source_relative_path: str, destination_suffix: str) -> str:
    """Build the marker with a comment syntax the destination file can parse.

    Hash comments are the default: every non-Markdown template managed today is
    source or configuration text where an HTML comment is a syntax error.
    """
    if destination_suffix in HTML_MARKER_SUFFIXES:
        return (
            f"<!-- {MANAGED_TEMPLATE_MARKER_PREFIX} {source_relative_path} -->\n"
            "<!-- Do not edit manually unless you remove this marker. -->\n"
        )
    return (
        f"# {MANAGED_TEMPLATE_MARKER_PREFIX} {source_relative_path}\n"
        "# Do not edit manually unless you remove this marker.\n"
    )


def _build_managed_template_content(
    source_relative_path: str, destination_relative_path: str, raw_content: str
) -> str:
    marker_block = _build_managed_marker(
        source_relative_path, Path(destination_relative_path).suffix.lower()
    )
    if raw_content.startswith(FRONTMATTER_DELIMITER):
        frontmatter_end = raw_content.find(
            f"\n{FRONTMATTER_DELIMITER}", len(FRONTMATTER_DELIMITER)
        )
        if frontmatter_end != -1:
            insertion_index = frontmatter_end + len(f"\n{FRONTMATTER_DELIMITER}")
            return (
                raw_content[:insertion_index]
                + "\n"
                + marker_block
                + "\n"
                + raw_content[insertion_index:].lstrip("\n")
            )
    if raw_content.startswith("#!"):
        shebang_end = raw_content.find("\n")
        if shebang_end == -1:
            return raw_content + "\n\n" + marker_block
        insertion_index = shebang_end + 1
        return (
            raw_content[:insertion_index]
            + marker_block
            + "\n"
            + raw_content[insertion_index:].lstrip("\n")
        )
    return marker_block + "\n" + raw_content


def _is_managed_template_content(content: str) -> bool:
    return MANAGED_TEMPLATE_MARKER_PREFIX in content


def _sync_agent_template(project_root: Path, template: AgentTemplate) -> TemplateSyncResult:
    repo_root = _repo_root()
    source_path = repo_root / template.source_relative_path
    raw_content = source_path.read_text(encoding="utf-8")
    managed_content = _build_managed_template_content(
        template.source_relative_path, template.destination_relative_path, raw_content
    )
    destination_path = project_root / template.destination_relative_path

    if not destination_path.exists():
        destination_path.parent.mkdir(parents=True, exist_ok=True)
        destination_path.write_text(managed_content, encoding="utf-8")
        return TemplateSyncResult(status="created", destination_path=destination_path)

    existing_content = destination_path.read_text(encoding="utf-8")
    if existing_content == managed_content:
        return TemplateSyncResult(status="up-to-date", destination_path=destination_path)

    if (
        _is_managed_template_content(existing_content)
        or existing_content == raw_content
    ):
        destination_path.write_text(managed_content, encoding="utf-8")
        return TemplateSyncResult(status="updated", destination_path=destination_path)

    return TemplateSyncResult(status="skipped-unmanaged", destination_path=destination_path)


def _build_claude_bridge_content(agents_md_name: str) -> str:
    return (
        f"<!-- {CLAUDE_BRIDGE_MARKER} -->\n"
        "<!-- Do not edit manually unless you remove this marker. -->\n"
        "\n"
        f"@{agents_md_name}\n"
    )


def _is_claude_bridge_content(content: str) -> bool:
    return CLAUDE_BRIDGE_MARKER in content


def sync_project_templates(project_root: Path) -> list[TemplateSyncResult]:
    manifest = _load_manifest(project_root)
    enabled_features = set(manifest.features)
    results: list[TemplateSyncResult] = []
    for agent in manifest.agents:
        for template in AGENT_TEMPLATES[agent]:
            if template.feature is not None and template.feature not in enabled_features:
                continue
            results.append(_sync_agent_template(project_root, template))
    for template in INFRA_TEMPLATES:
        if template.feature is not None and template.feature not in enabled_features:
            continue
        results.append(_sync_agent_template(project_root, template))
    return results


@app.command()
def render(
    project_root: Annotated[Path, PROJECT_ROOT_OPTION],
    output_name: Annotated[str, OUTPUT_NAME_OPTION] = DEFAULT_OUTPUT_NAME,
) -> None:
    """Render AGENTS.md for a downstream project."""

    result = build_rendered_content(project_root=project_root, output_name=output_name)
    write_rendered_content(result)
    typer.echo(f"Rendered {result.output_path}")


@app.command()
def update(
    project_root: Annotated[Path, PROJECT_ROOT_OPTION],
    output_name: Annotated[str, OUTPUT_NAME_OPTION] = DEFAULT_OUTPUT_NAME,
) -> None:
    """Alias for render, intended for explicit standards updates."""

    result = build_rendered_content(project_root=project_root, output_name=output_name)
    write_rendered_content(result)
    typer.echo(f"Updated {result.output_path}")


@app.command()
def check(
    project_root: Annotated[Path, PROJECT_ROOT_OPTION],
    output_name: Annotated[str, OUTPUT_NAME_OPTION] = DEFAULT_OUTPUT_NAME,
) -> None:
    """Check that the generated file matches the current manifest and standards."""

    result = build_rendered_content(project_root=project_root, output_name=output_name)
    ensure_generated_file(result)
    existing = result.output_path.read_text(encoding="utf-8")
    if existing != result.content:
        raise SyncError(
            f"{result.output_path} is out of date. Run the render or update command."
        )
    typer.echo(f"{result.output_path} is up to date")


@app.command("init-project")
def init_project(
    project_root: Annotated[Path, PROJECT_ROOT_OPTION],
) -> None:
    """Create starter manifest and project-local override templates."""

    repo_root = _repo_root()
    created_paths: list[Path] = []
    manifest_created = _copy_template_if_missing(
        repo_root / "templates" / "project_manifest.toml",
        project_root / MANIFEST_FILE_NAME,
    )
    if manifest_created:
        _seed_manifest_release_version(project_root)
        created_paths.append(project_root / MANIFEST_FILE_NAME)

    project_rules_created = _copy_template_if_missing(
        repo_root / "templates" / "project_rules.md",
        project_root / "ai" / "project-rules.md",
    )
    if project_rules_created:
        created_paths.append(project_root / "ai" / "project-rules.md")

    template_results: list[TemplateSyncResult] = []
    manifest_path = project_root / MANIFEST_FILE_NAME
    if manifest_path.exists():
        template_results = sync_project_templates(project_root)

    if not created_paths and not template_results:
        typer.echo("No files created. Project is already initialized.")
        return

    for path in created_paths:
        typer.echo(f"Created {path}")
    for result in template_results:
        typer.echo(f"{result.status.capitalize()} {result.destination_path}")


@app.command("sync-templates")
def sync_templates(
    project_root: Annotated[Path, PROJECT_ROOT_OPTION],
) -> None:
    """Sync agent-specific managed templates declared in ai.project.toml."""

    results = sync_project_templates(project_root)
    if not results:
        typer.echo("No agent templates configured in ai.project.toml.")
        return

    for result in results:
        typer.echo(f"{result.status.capitalize()} {result.destination_path}")


@app.command("init-claude-bridge")
def init_claude_bridge(
    project_root: Annotated[Path, PROJECT_ROOT_OPTION],
    output_name: Annotated[str, OUTPUT_NAME_OPTION] = DEFAULT_OUTPUT_NAME,
) -> None:
    """Create a thin CLAUDE.md that imports AGENTS.md for Claude Code compatibility."""

    bridge_path = project_root / CLAUDE_BRIDGE_FILE
    bridge_content = _build_claude_bridge_content(output_name)

    if bridge_path.exists():
        existing = bridge_path.read_text(encoding="utf-8")
        if existing == bridge_content:
            typer.echo(f"{bridge_path} is already up to date")
            return
        if not _is_claude_bridge_content(existing):
            typer.echo(f"Skipped {bridge_path}: exists and is not managed by ai-standards")
            return
        bridge_path.write_text(bridge_content, encoding="utf-8")
        typer.echo(f"Updated {bridge_path}")
        return

    bridge_path.write_text(bridge_content, encoding="utf-8")
    typer.echo(f"Created {bridge_path}")


@dataclass(frozen=True)
class DoctorFinding:
    severity: str
    code: str
    location: str
    message: str


@dataclass(frozen=True)
class DoctorReport:
    findings: tuple[DoctorFinding, ...]
    notes_checked: int
    knowledge_tree: Path

    @property
    def error_count(self) -> int:
        return sum(1 for finding in self.findings if finding.severity == SEVERITY_ERROR)

    @property
    def warning_count(self) -> int:
        return sum(1 for finding in self.findings if finding.severity == SEVERITY_WARNING)


def _is_inside(path: Path, container: Path) -> bool:
    """Return True when ``path`` sits at or below ``container``."""
    try:
        path.relative_to(container)
    except ValueError:
        return False
    return True


def _yaml_scalar(value: str) -> str:
    """Render a string as a YAML scalar, quoting it when a plain one would not parse.

    A title lifted from a heading may contain a colon — `# DECISION: something` is the
    common case — and an unquoted colon turns the value into a nested mapping.
    """
    plain_is_safe = (
        bool(value)
        and value == value.strip()
        and ": " not in value
        and not value.endswith(":")
        and " #" not in value
        and value[0] not in "-?:,[]{}#&*!|>'\"%@`"
    )
    if plain_is_safe:
        return value
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _frontmatter_title(raw_content: str) -> str | None:
    """Read the top-level ``title`` value without pulling in a YAML dependency."""
    block, _ = _split_frontmatter(raw_content)
    if block is None:
        return None
    for line in block.splitlines():
        if line.startswith("title:"):
            value = line[len("title:") :].strip()
            if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
                inner = value[1:-1]
                return inner.replace('\\"', '"').replace("\\\\", "\\") if value[0] == '"' else inner
            return value
    return None


def _first_heading(raw_content: str) -> str | None:
    _, body = _split_frontmatter(raw_content)
    for line in body.splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return None


class UnreadableFile(SyncError):
    """Raised when a file an audit must inspect cannot be decoded as UTF-8 text."""


def _read_audit_text(path: Path) -> str:
    """Read a file for auditing, translating a low-level failure into an audit error.

    An audit runs against trees that may already be damaged, so callers catch this and
    turn it into a finding rather than aborting the whole run.
    """
    try:
        return path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError) as exc:
        raise UnreadableFile(f"{path} is not valid UTF-8 text: {exc}") from exc


def _audit_override_placement(
    project_root: Path,
    manifest: Manifest,
    knowledge_tree: Path,
) -> list[DoctorFinding]:
    """Rendering inputs are concatenated verbatim, so they must stay out of the tree."""
    findings: list[DoctorFinding] = []
    declared = [(path, True) for path in manifest.local_overrides]
    declared += [(path, False) for path in manifest.optional_local_overrides]

    for relative_path, required in declared:
        override_path = project_root / relative_path
        if _is_inside(override_path, knowledge_tree):
            findings.append(
                DoctorFinding(
                    severity=SEVERITY_ERROR,
                    code="override-inside-knowledge-tree",
                    location=relative_path,
                    message=(
                        "Rendering input lives inside the knowledge tree. An indexer will "
                        "treat it as a note, and its content is concatenated verbatim into "
                        "the generated file. Move it outside, for example to 'ai/'."
                    ),
                )
            )
        if not override_path.exists():
            if required:
                findings.append(
                    DoctorFinding(
                        severity=SEVERITY_ERROR,
                        code="override-missing",
                        location=relative_path,
                        message="Declared local override does not exist; rendering will fail.",
                    )
                )
            continue
        try:
            override_content = _read_audit_text(override_path)
        except UnreadableFile:
            findings.append(
                DoctorFinding(
                    severity=SEVERITY_ERROR,
                    code="override-unreadable",
                    location=relative_path,
                    message="Local override is not valid UTF-8 text; rendering will fail.",
                )
            )
            continue
        if _split_frontmatter(override_content)[0] is not None:
            findings.append(
                DoctorFinding(
                    severity=SEVERITY_WARNING,
                    code="override-carries-frontmatter",
                    location=relative_path,
                    message=(
                        "Rendering input starts with frontmatter, which usually means an "
                        "indexer is treating it as a note. Rendering strips the block, but "
                        "the file itself keeps being rewritten."
                    ),
                )
            )
    return findings


def _audit_note(
    note_path: Path,
    relative_path: str,
    name_is_governed: bool,
) -> list[DoctorFinding]:
    try:
        raw_content = _read_audit_text(note_path)
    except UnreadableFile:
        return [
            DoctorFinding(
                severity=SEVERITY_ERROR,
                code="note-unreadable",
                location=relative_path,
                message="Note is not valid UTF-8 text and cannot be indexed.",
            )
        ]
    findings: list[DoctorFinding] = []

    title = _frontmatter_title(raw_content)
    if _split_frontmatter(raw_content)[0] is None:
        findings.append(
            DoctorFinding(
                severity=SEVERITY_WARNING,
                code="note-without-frontmatter",
                location=relative_path,
                message=(
                    "Note has no frontmatter, so its title falls back to the file name and "
                    "its type falls back to the default."
                ),
            )
        )
    elif title is None:
        findings.append(
            DoctorFinding(
                severity=SEVERITY_WARNING,
                code="note-without-title",
                location=relative_path,
                message="Frontmatter has no 'title'; identity falls back to the file name.",
            )
        )

    heading = _first_heading(raw_content)
    if heading is None:
        findings.append(
            DoctorFinding(
                severity=SEVERITY_WARNING,
                code="note-without-heading",
                location=relative_path,
                message="Note has no top-level '# ' heading.",
            )
        )
    elif title is not None and heading != title:
        findings.append(
            DoctorFinding(
                severity=SEVERITY_WARNING,
                code="note-title-heading-mismatch",
                location=relative_path,
                message=f"Frontmatter title {title!r} does not match heading {heading!r}.",
            )
        )

    stem = LANGUAGE_SUFFIX_PATTERN.sub("", Path(relative_path).stem)
    if name_is_governed and not NOTE_NAME_PATTERN.match(stem):
        findings.append(
            DoctorFinding(
                severity=SEVERITY_WARNING,
                code="note-name-against-convention",
                location=relative_path,
                message=(
                    "File name is not a lowercase ASCII slug of the form "
                    "'YYYY-MM-DD-topic-slug.md'. Renaming needs a meaningful slug, so it is "
                    "reported rather than fixed automatically."
                ),
            )
        )

    _, note_body = _split_frontmatter(raw_content)
    if not OBSERVATION_PATTERN.search(note_body):
        findings.append(
            DoctorFinding(
                severity=SEVERITY_WARNING,
                code="note-without-observations",
                location=relative_path,
                message="Note contributes no observations to the knowledge graph.",
            )
        )
    if not RELATION_PATTERN.search(note_body):
        findings.append(
            DoctorFinding(
                severity=SEVERITY_WARNING,
                code="note-without-relations",
                location=relative_path,
                message="Note contributes no relations to the knowledge graph.",
            )
        )
    return findings


def _audit_knowledge_tree(
    project_root: Path,
    knowledge_tree: Path,
    manifest: Manifest,
    dated_note_directories: tuple[str, ...],
) -> tuple[list[DoctorFinding], int]:
    if not knowledge_tree.is_dir():
        return (
            [
                DoctorFinding(
                    severity=SEVERITY_WARNING,
                    code="knowledge-tree-missing",
                    location=str(knowledge_tree.name),
                    message="Knowledge tree directory does not exist; nothing to audit.",
                )
            ],
            0,
        )

    declared_overrides = {
        (project_root / path).resolve()
        for path in [*manifest.local_overrides, *manifest.optional_local_overrides]
    }

    findings: list[DoctorFinding] = []
    archive_dir = knowledge_tree / ARCHIVE_DIRECTORY_NAME
    for directory in sorted(knowledge_tree.rglob("*")):
        if _is_inside(directory, archive_dir):
            continue
        if directory.is_dir() and not any(directory.iterdir()):
            findings.append(
                DoctorFinding(
                    severity=SEVERITY_WARNING,
                    code="empty-directory",
                    location=directory.relative_to(project_root).as_posix(),
                    message="Directory inside the knowledge tree holds nothing.",
                )
            )

    notes_checked = 0
    for note_path in sorted(knowledge_tree.rglob("*.md")):
        if note_path.resolve() in declared_overrides:
            continue
        if _is_inside(note_path, archive_dir):
            continue
        notes_checked += 1
        relative_path = note_path.relative_to(project_root).as_posix()
        governed_directories = tuple(knowledge_tree / name for name in dated_note_directories)
        name_is_governed = any(
            _is_inside(note_path, directory) for directory in governed_directories
        )
        findings.extend(_audit_note(note_path, relative_path, name_is_governed))
    return findings, notes_checked


def _looks_like_a_knowledge_tree(root: Path) -> bool:
    """Judge whether an indexed root holds notes or a repository.

    A knowledge tree carries Markdown and nothing else at its top level. A repository or a
    workspace umbrella gives itself away immediately: a `.git` directory, or build and
    configuration files sitting beside the documentation.
    """
    if (root / ".git").is_dir():
        return False
    try:
        entries = list(root.iterdir())
    except OSError:
        return True
    return not any(
        entry.is_file() and not entry.name.startswith(".") and entry.suffix != ".md"
        for entry in entries
    )


def _audit_indexer_config(
    project_root: Path,
    knowledge_tree: Path,
    indexer_config: Path,
) -> list[DoctorFinding]:
    """Check the indexer's own configuration when the project enables the feature."""
    if not indexer_config.exists():
        return []
    try:
        config = cast(dict[str, object], json.loads(indexer_config.read_text(encoding="utf-8")))
    except (OSError, json.JSONDecodeError):
        return [
            DoctorFinding(
                severity=SEVERITY_WARNING,
                code="indexer-config-unreadable",
                location=str(indexer_config),
                message="Indexer configuration exists but could not be parsed.",
            )
        ]

    findings: list[DoctorFinding] = []
    projects = config.get("projects")
    matched_tree = False
    other_repository_roots: list[str] = []
    if isinstance(projects, dict):
        for name, entry in cast(dict[str, object], projects).items():
            raw_path = entry.get("path") if isinstance(entry, dict) else entry
            if not isinstance(raw_path, str):
                continue
            indexed_root = Path(raw_path).expanduser().resolve()
            # Trigger: another project indexes a directory that is itself a repository.
            # Why: the write-guard flags are global, so those roots decide whether this
            #      project may turn them off, and a single-project audit is blind to them.
            # Outcome: name them, turning an open question into a list of roots to narrow.
            # This project's own root is reported separately as indexed-repository-root,
            # so listing it again among the roots that block a global setting is noise.
            if (
                indexed_root not in (knowledge_tree, project_root)
                and not _looks_like_a_knowledge_tree(indexed_root)
            ):
                other_repository_roots.append(f"{name} -> {indexed_root}")
            if indexed_root == knowledge_tree:
                matched_tree = True
            elif indexed_root == project_root:
                findings.append(
                    DoctorFinding(
                        severity=SEVERITY_ERROR,
                        code="indexed-repository-root",
                        location=f"{indexer_config}:{name}",
                        message=(
                            "Indexed root is the repository root. It pulls vendored files, "
                            f"build artifacts, and generated output into the graph. Point it "
                            f"at {knowledge_tree} instead."
                        ),
                    )
                )
    if not matched_tree:
        findings.append(
            DoctorFinding(
                severity=SEVERITY_WARNING,
                code="knowledge-tree-not-indexed",
                location=str(indexer_config),
                message=f"No indexer project points at {knowledge_tree}.",
            )
        )

    if config.get("disable_permalinks") is True:
        blocked = (
            " The setting is global, so it cannot be turned on until every indexed root is "
            "a knowledge tree; see other-indexed-repository-roots for the ones left."
            if other_repository_roots
            else ""
        )
        findings.append(
            DoctorFinding(
                severity=SEVERITY_WARNING,
                code="permalinks-disabled",
                location=f"{indexer_config}:disable_permalinks",
                message=(
                    "Permalinks are disabled, so 'memory://' addressing and graph traversal "
                    "resolve against nothing and retrieval degrades to plain search. Keep "
                    "this only as a fallback for a tree that cannot be narrowed yet." + blocked
                ),
            )
        )
    if other_repository_roots:
        findings.append(
            DoctorFinding(
                severity=SEVERITY_WARNING,
                code="other-indexed-repository-roots",
                location=str(indexer_config),
                message=(
                    "Other projects index a repository root rather than a knowledge tree, so "
                    "global indexer settings cannot be changed without affecting them: "
                    + "; ".join(sorted(other_repository_roots))
                ),
            )
        )

    archive_dir = knowledge_tree / ARCHIVE_DIRECTORY_NAME
    if not archive_dir.is_dir():
        return findings
    bmignore_path = indexer_config.parent / ".bmignore"
    if not _archive_is_excluded(bmignore_path):
        findings.append(
            DoctorFinding(
                severity=SEVERITY_WARNING,
                code="archive-not-excluded",
                location=f"{bmignore_path}:patterns",
                message=(
                    f"The archive at {archive_dir} holds verbatim sources that stay out of the "
                    "graph, but no '.bmignore' pattern excludes it. Add 'archive/' beside "
                    f"{indexer_config}, or sync will index transcripts into the graph."
                ),
            )
        )
    return findings


def _load_bmignore_patterns(path: Path) -> list[str]:
    try:
        lines = path.read_text(encoding="utf-8").splitlines()
    except OSError:
        return []
    return [line.strip() for line in lines if line.strip() and not line.strip().startswith("#")]


def _archive_is_excluded(bmignore_path: Path) -> bool:
    """Check that a `.bmignore` carries an exclusion the sync matcher will honour.

    The knowledge-tree matcher ignores a directory when some path segment equals
    the pattern name, so `archive/`, `archive`, `archive/*` and their
    root-anchored forms all exclude the subtree at any depth, while
    `archivefoo/` does not.
    """
    for pattern in _load_bmignore_patterns(bmignore_path):
        normalized = pattern.strip("/")
        if normalized.split("/")[0] == ARCHIVE_DIRECTORY_NAME:
            return True
    return False


def run_doctor(
    project_root: Path,
    knowledge_tree_name: str | None = None,
    indexer_config: Path | None = None,
) -> DoctorReport:
    """Audit how a project is wired for Markdown knowledge retrieval.

    Knowledge-tree settings resolve explicit argument first, then the project manifest,
    then the built-in default, so a project can declare its own layout once.
    """
    # Paths are compared against a resolved knowledge tree, so the root is normalized
    # here rather than relying on the caller: the CLI resolves it, the API need not.
    project_root = project_root.resolve()
    manifest = _load_manifest(project_root)
    tree_name = knowledge_tree_name or manifest.knowledge_tree or DEFAULT_KNOWLEDGE_TREE
    knowledge_tree = (project_root / tree_name).resolve()
    dated_note_directories = (
        tuple(manifest.dated_note_directories)
        if manifest.dated_note_directories is not None
        else DEFAULT_DATED_NOTE_DIRECTORIES
    )

    findings = _audit_override_placement(project_root, manifest, knowledge_tree)
    tree_findings, notes_checked = _audit_knowledge_tree(
        project_root, knowledge_tree, manifest, dated_note_directories
    )
    findings.extend(tree_findings)

    if "basic-memory" in manifest.features:
        findings.extend(
            _audit_indexer_config(
                project_root,
                knowledge_tree,
                DEFAULT_INDEXER_CONFIG if indexer_config is None else indexer_config,
            )
        )

    return DoctorReport(
        findings=tuple(findings),
        notes_checked=notes_checked,
        knowledge_tree=knowledge_tree,
    )


FIXABLE_CODES = frozenset(
    {
        "override-inside-knowledge-tree",
        "override-carries-frontmatter",
        "note-without-frontmatter",
        "note-without-title",
        "note-without-heading",
        "note-title-heading-mismatch",
        "empty-directory",
    }
)


@dataclass(frozen=True)
class RepairAction:
    code: str
    location: str
    description: str


def _repair_override_placement(
    project_root: Path,
    relative_path: str,
    override_directory: str,
) -> RepairAction:
    """Move a rendering input out of the knowledge tree and repoint the manifest.

    The move and the manifest rewrite have to succeed together: a moved file with a stale
    manifest leaves the project unable to render at all. Everything that can be checked is
    therefore checked before the filesystem is touched, and the move is rolled back if the
    rewrite still fails.
    """
    source = project_root / relative_path
    destination_relative = f"{override_directory}/{Path(relative_path).name}"
    destination = project_root / destination_relative
    if destination.exists():
        raise SyncError(f"Cannot move {relative_path}: {destination_relative} already exists")

    # tomllib only reads, and the manifest is hand-maintained, so the declared path is
    # repointed textually to preserve formatting — which requires it to appear verbatim.
    manifest_path = project_root / MANIFEST_FILE_NAME
    manifest_content = manifest_path.read_text(encoding="utf-8")
    quoted_old = f'"{relative_path}"'
    if quoted_old not in manifest_content:
        raise SyncError(
            f"Cannot repoint {relative_path}: {MANIFEST_FILE_NAME} does not contain it as a "
            f"double-quoted string. Nothing was moved; repoint it by hand."
        )

    moved = False
    if source.exists():
        destination.parent.mkdir(parents=True, exist_ok=True)
        source.rename(destination)
        moved = True
    try:
        manifest_path.write_text(
            manifest_content.replace(quoted_old, f'"{destination_relative}"'),
            encoding="utf-8",
        )
    except OSError as error:
        if moved:
            destination.rename(source)
        raise SyncError(
            f"Cannot repoint {relative_path} in {MANIFEST_FILE_NAME}: {error}"
        ) from error

    return RepairAction(
        code="override-inside-knowledge-tree",
        location=relative_path,
        description=f"moved to {destination_relative} and repointed in {MANIFEST_FILE_NAME}",
    )


def _repair_note(note_path: Path, relative_path: str, codes: set[str]) -> list[RepairAction]:
    """Apply the structural note fixes that do not require judgement."""
    try:
        raw_content = _read_audit_text(note_path)
    except UnreadableFile:
        # Already surfaced as note-unreadable by the audit; nothing here can repair it.
        return []

    actions: list[RepairAction] = []
    heading = _first_heading(raw_content)
    stem = note_path.stem

    if "note-without-frontmatter" in codes:
        title = heading or stem
        raw_content = (
            f"{FRONTMATTER_DELIMITER}title: {_yaml_scalar(title)}\n"
            f"{FRONTMATTER_DELIMITER}\n{raw_content}"
        )
        actions.append(
            RepairAction(
                "note-without-frontmatter", relative_path, f"added frontmatter title {title!r}"
            )
        )
    elif "note-without-title" in codes:
        title = heading or stem
        raw_content = raw_content.replace(
            FRONTMATTER_DELIMITER, f"{FRONTMATTER_DELIMITER}title: {_yaml_scalar(title)}\n", 1
        )
        actions.append(
            RepairAction("note-without-title", relative_path, f"added frontmatter title {title!r}")
        )

    title = _frontmatter_title(raw_content) or stem
    _, body = _split_frontmatter(raw_content)
    prefix = raw_content[: len(raw_content) - len(body)]

    if "note-without-heading" in codes:
        raw_content = f"{prefix}\n# {title}\n\n{body.lstrip()}"
        actions.append(
            RepairAction("note-without-heading", relative_path, f"inserted heading '# {title}'")
        )
    elif "note-title-heading-mismatch" in codes and heading is not None:
        # The frontmatter title is the graph identity, so the heading follows it. Matching
        # whole lines matters: a substring replacement would rewrite a deeper heading that
        # merely starts with the same text.
        lines = body.splitlines(keepends=True)
        for index, line in enumerate(lines):
            if line.startswith("# "):
                lines[index] = f"# {title}\n"
                break
        raw_content = prefix + "".join(lines)
        actions.append(
            RepairAction(
                "note-title-heading-mismatch",
                relative_path,
                f"aligned heading with title {title!r}",
            )
        )

    if actions:
        note_path.write_text(raw_content, encoding="utf-8")
    return actions


def run_repair(
    project_root: Path,
    report: DoctorReport,
    override_directory: str = DEFAULT_OVERRIDE_DIRECTORY,
) -> list[RepairAction]:
    """Apply every deterministic repair the report calls for.

    Findings that need a naming or content decision are deliberately left alone; they
    belong to the audit skill, which proposes them for confirmation.
    """
    project_root = project_root.resolve()
    actions: list[RepairAction] = []

    for finding in report.findings:
        if finding.code == "override-inside-knowledge-tree":
            actions.append(
                _repair_override_placement(project_root, finding.location, override_directory)
            )

    # Runs after the move, so the leftover block is stripped at the override's new path.
    # A rendering input has no use for frontmatter: the renderer drops it either way.
    for finding in report.findings:
        if finding.code != "override-carries-frontmatter":
            continue
        moved = next(
            (a.description for a in actions if a.location == finding.location), ""
        )
        relative_path = (
            moved.split(" ", 2)[2].split(" and ")[0]
            if moved.startswith("moved to ")
            else finding.location
        )
        override_path = project_root / relative_path
        if not override_path.exists():
            continue
        block, body = _split_frontmatter(override_path.read_text(encoding="utf-8"))
        if block is None:
            continue
        override_path.write_text(body.lstrip("\n"), encoding="utf-8")
        actions.append(
            RepairAction(
                "override-carries-frontmatter", relative_path, "stripped leftover frontmatter"
            )
        )

    note_codes: dict[str, set[str]] = {}
    for finding in report.findings:
        if finding.code in FIXABLE_CODES and finding.code.startswith("note-"):
            note_codes.setdefault(finding.location, set()).add(finding.code)
    for relative_path, codes in sorted(note_codes.items()):
        actions.extend(_repair_note(project_root / relative_path, relative_path, codes))

    # Swept last and deepest first, so directories emptied by the repairs above — a
    # knowledge-tree folder that held nothing but a rendering input, for instance — go too.
    for directory in sorted(
        (path for path in report.knowledge_tree.rglob("*") if path.is_dir()),
        key=lambda path: len(path.parts),
        reverse=True,
    ):
        if not any(directory.iterdir()):
            location = directory.relative_to(project_root).as_posix()
            directory.rmdir()
            actions.append(RepairAction("empty-directory", location, "removed"))

    return actions


def _echo_findings(report: DoctorReport) -> None:
    for finding in report.findings:
        marker = "ERROR" if finding.severity == SEVERITY_ERROR else "warn "
        fixable = " (fixable)" if finding.code in FIXABLE_CODES else ""
        typer.echo(f"{marker} [{finding.code}]{fixable} {finding.location}")
        typer.echo(f"      {finding.message}")

    typer.echo(
        f"Checked {report.notes_checked} notes under {report.knowledge_tree}: "
        f"{report.error_count} errors, {report.warning_count} warnings"
    )


@app.command()
def doctor(
    project_root: Annotated[Path, PROJECT_ROOT_OPTION],
    knowledge_tree: Annotated[
        str | None,
        typer.Option(help="Directory holding the notes; overrides the manifest."),
    ] = None,
    indexer_config: Annotated[
        Path | None,
        typer.Option(help="Indexer configuration file to inspect."),
    ] = None,
    fix: Annotated[
        bool,
        typer.Option("--fix", help="Apply the repairs that need no judgement."),
    ] = False,
    override_directory: Annotated[
        str,
        typer.Option(help="Directory that rendering inputs are moved into by --fix."),
    ] = DEFAULT_OVERRIDE_DIRECTORY,
) -> None:
    """Audit how the project is wired for Markdown knowledge retrieval."""

    report = run_doctor(project_root, knowledge_tree, indexer_config)
    _echo_findings(report)

    if not fix:
        if any(finding.code in FIXABLE_CODES for finding in report.findings):
            typer.echo("Re-run with --fix to apply the repairs marked fixable.")
        if report.error_count:
            raise typer.Exit(code=1)
        return

    if not any((parent / ".git").exists() for parent in (project_root, *project_root.parents)):
        typer.echo(
            "Warning: no git repository at the project root, so --fix cannot be undone with git."
        )

    actions = run_repair(project_root, report, override_directory)
    if not actions:
        typer.echo("Nothing to fix automatically.")
    for action in actions:
        typer.echo(f"fixed [{action.code}] {action.location}: {action.description}")

    if any(action.code == "override-inside-knowledge-tree" for action in actions):
        typer.echo("A rendering input moved; run 'ai-sync render' to refresh the generated file.")

    remaining = run_doctor(project_root, knowledge_tree, indexer_config)
    typer.echo(
        f"Remaining: {remaining.error_count} errors, {remaining.warning_count} warnings"
    )
    if remaining.error_count:
        raise typer.Exit(code=1)


def main() -> None:
    try:
        app()
    except SyncError as error:
        typer.echo(f"Error: {error}", err=True)
        raise typer.Exit(code=1) from error


if __name__ == "__main__":
    main()
